from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "workstream6-canonical-authority.yaml"
OUTPUT_PATH = ROOT / "repository" / "canonical-authority-registry.json"
REPORT_PATH = ROOT / "reports" / "workstream6-canonical-authority-evidence.md"


def _load_source() -> tuple[dict[str, Any], str]:
    text = SOURCE_PATH.read_text(encoding="utf-8")
    value = yaml.safe_load(text)
    if not isinstance(value, dict):
        raise ValueError("WS6.4 source must contain a mapping")
    if value.get("work_package_id") != "WS6.4":
        raise ValueError("WS6.4 source has the wrong work package")
    return value, text


def build_records() -> tuple[dict[str, Any], str, str]:
    source, source_text = _load_source()
    exact = source.get("exact_records")
    rules = source.get("classification_rules")
    external = source.get("external_records")
    if not isinstance(exact, list) or len(exact) != 43:
        raise ValueError("WS6.4 successor registry must define exactly 43 exact records")
    if not isinstance(rules, list) or len(rules) != 11:
        raise ValueError("WS6.4 must define exactly 11 classification rules")
    if not isinstance(external, list) or len(external) != 3:
        raise ValueError("WS6.4 must define exactly three external records")
    if not source_text.endswith("\n"):
        source_text += "\n"
    report = "\n".join([
        "# WS6.4 canonical authority and evidence registry", "", "<!-- Generated by scripts/build_workstream6_canonical_authority.py. -->", "",
        f"- Base main: `{source['base_main_sha']}`", f"- Exact authority records: `{len(exact)}`", f"- Ordered classification rules: `{len(rules)}`", f"- External authority records: `{len(external)}`",
        "- Sole current machine handoff: `handoff/codex-phase0-handoff.json`", "- Sole current generated issue body: `handoff/codex-phase0-issue-final.md`", "- Current required workflow: `.github/workflows/workstream6-final-pre-codex.yml`", "- Current required workflow identity: `contracts/workstream6-required-workflow-identity.json`", "- Current actionable issue: `#1`", "- Current manual gate: `#19`", "- Superseded duplicate issue: `#2`", "- Closed defects: `WS6-CONSIST-001`, `WS6-CONSIST-007`", "- Remaining blocking defect: `WS6-BLOCK-006`", "- Current status reconciled to integrated `main` through WS6.7; later WS6 packages remain unintegrated.", "- Every authority and implementation boundary remains fail-closed.", "",
        "The semantic validator parses both current read orders, scans every configured", "authority and evidence root, rejects unclassified paths, and enforces all", "current-authority uniqueness constraints.", "", "Historical WS6.4 package sequencing remains retained provenance; it does not override current integrated status.", "",
    ])
    return source, source_text, report


def main() -> None:
    source, output, report = build_records()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(output, encoding="utf-8")
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"Built WS6.4 canonical authority registry: exact={len(source['exact_records'])}, rules={len(source['classification_rules'])}, external={len(source['external_records'])}, integrated_through=WS6.7, codex_start_authorized=false.")


if __name__ == "__main__":
    main()
