from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "pcfa06-hermes-bounded-adoption-refresh.yaml"
OUTPUT_PATH = ROOT / "repository" / "pcfa06-hermes-bounded-adoption-refresh.json"
REPORT_PATH = ROOT / "reports" / "pcfa06-hermes-bounded-adoption-refresh-evidence.md"


def _load_source() -> dict[str, Any]:
    value = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("PCFA-06 Hermes refresh source must contain a mapping")
    return value


def _canonical(value: object) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"


def build_records() -> tuple[dict[str, Any], str]:
    source = _load_source()
    if source.get("work_package_id") != "PCFA-06":
        raise ValueError("PCFA-06 work-package identity drifted")
    if source.get("contract_id") != "HERMES-BOUNDED-ADOPTION-REFRESH":
        raise ValueError("PCFA-06 contract identity drifted")

    record = dict(source)
    record["generated_from"] = str(SOURCE_PATH.relative_to(ROOT))
    capabilities = record.get("capability_assessments", [])
    principles = record.get("operating_principles", [])
    evidence = record.get("upstream_evidence", [])
    phases = sorted(
        {
            phase
            for item in capabilities
            if isinstance(item, dict)
            for phase in item.get("owning_imp_phases", [])
        }
    )
    report = "\n".join(
        [
            "# PCFA-06 Hermes bounded-adoption refresh evidence",
            "",
            "<!-- Generated by scripts/build_pcfa06_hermes_refresh.py. -->",
            "",
            f"- Work package: `{record['work_package_id']}`",
            f"- Contract: `{record['contract_id']}`",
            f"- Assessment date: `{record['assessment_date']}`",
            f"- Stable release: `{record['upstream_baseline']['stable_release']}`",
            f"- Stable tag: `{record['upstream_baseline']['stable_tag']}`",
            f"- Stable commit: `{record['upstream_baseline']['stable_commit']}`",
            "- Stable release changed from PCR-06: `false`",
            f"- Operating principles: `{len(principles)}`",
            f"- Upstream evidence records: `{len(evidence)}`",
            f"- Capability assessments: `{len(capabilities)}`",
            f"- Owning IMP phases represented: `{len(phases)}`",
            "- Raw `/goal` completion authority: `false`; offdata acceptance remains authoritative.",
            "- Raw top-level background delegation: `false`; initial adapter concurrency remains `1`.",
            "- `/learn` and `/journey`: candidate/suggestion or read-only use only; no canonical promotion.",
            "- Mixture-of-Agents: candidate only behind the offdata model router; never independent QA by itself.",
            "- Hermes memory, curator, gateway, cron, messaging, MCP/tool gateway and Codex app-server runtime remain noncanonical, deferred or denied pending later gates.",
            "- Every capability remains `planned_not_implemented`.",
            "- PCFA-07 global obligation/test reconciliation and PCFA-08 final acceptance remain required.",
            "- `codex_start_authorized=false`; installation, runtime activation, background execution, model fan-out, external actions and autonomous merge remain denied.",
            "",
        ]
    )
    return record, report


def main() -> None:
    record, report = build_records()
    OUTPUT_PATH.write_text(_canonical(record), encoding="utf-8")
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(
        "Built PCFA-06 Hermes bounded-adoption refresh: "
        f"stable_release={record['upstream_baseline']['stable_release']}, "
        f"capabilities={len(record['capability_assessments'])}, "
        f"principles={len(record['operating_principles'])}, "
        "planned_not_implemented=true, hermes_activation_authorized=false, "
        "codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
