from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "configs" / "workstream6-issue-backlog-normalization.yaml"
CONTRACT = ROOT / "contracts" / "workstream6-issue-backlog-normalization.json"
REPORT = ROOT / "reports" / "workstream6-issue-backlog-normalization-evidence.md"
PHASE_HEADING = re.compile(r"^## (IMP-P([0-9]+)) — (.+)$", re.MULTILINE)
TASK_HEADING = re.compile(r"^### (P[0-9]+\.[0-9]+) (.+)$", re.MULTILINE)


def _load_yaml(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a mapping")
    return value


def _sha256(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _parse_backlog(text: str, first: int, last: int) -> list[dict[str, Any]]:
    matches = list(PHASE_HEADING.finditer(text))
    phases: list[dict[str, Any]] = []
    for index, match in enumerate(matches):
        number = int(match.group(2))
        if number < first or number > last:
            continue
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        section = text[match.end():end]
        tasks = [
            {"id": task.group(1), "title": task.group(2).strip()}
            for task in TASK_HEADING.finditer(section)
        ]
        gate_heading = f"### {match.group(1)} gate"
        gate = ""
        if gate_heading in section:
            gate = (
                "Canonical gate: `docs/11-BUILD-BACKLOG.md` — "
                f"`{match.group(1)} gate`."
            )
        phases.append(
            {
                "id": match.group(1),
                "number": number,
                "title": match.group(3).strip(),
                "depends_on": ["IMP-P0" if number == 1 else f"IMP-P{number - 1}"],
                "tasks": tasks,
                "gate": gate,
                "draft_only": True,
                "live_issue_created": False,
                "implementation_authorized": False,
            }
        )
    expected = [f"IMP-P{number}" for number in range(first, last + 1)]
    if [phase["id"] for phase in phases] != expected:
        raise ValueError("backlog must contain IMP-P1 through IMP-P12 in order")
    if any(not phase["tasks"] or not phase["gate"] for phase in phases):
        raise ValueError("every future phase must contain tasks and a gate")
    return phases


def _pack_body(phases: list[dict[str, Any]]) -> str:
    sections = [
        "# [BLOCKED DRAFT PACK] Future implementation issues — IMP-P1 through IMP-P12",
        "",
        "> [!CAUTION]",
        "> **NOT AUTHORISED TO START.** These are repository-only issue drafts. "
        "They are not live assignments and grant no implementation authority.",
        "",
        "Issue #1 remains the only actionable implementation assignment and is limited to permit-gated IMP-P0. "
        "Issue #19 remains the only manual pre-launch gate.",
        "",
    ]
    for phase in phases:
        tasks = "\n".join(
            f"- [ ] `{task['id']}` — {task['title']}" for task in phase["tasks"]
        )
        sections.extend(
            [
                f"## [BLOCKED DRAFT] {phase['id']} — {phase['title']}",
                "",
                f"- Dependency: `{phase['depends_on'][0]}`",
                "- State: blocked draft",
                "- Live GitHub issue created: `false`",
                "- Implementation authorized: `false`",
                "- `codex_start_authorized=false`",
                "",
                "### Planned tasks",
                "",
                tasks,
                "",
                "### Phase gate",
                "",
                phase["gate"],
                "",
                "### Activation rule",
                "",
                "Create a live issue only after every dependency is complete and the Founder explicitly authorizes this exact phase. "
                "Repository presence, labels, milestones, workflow success or earlier instructions do not authorize implementation.",
                "",
            ]
        )
    sections.extend(
        [
            "## Rollback",
            "",
            "Delete or replace this blocked draft pack without changing live issue authority. "
            "Never reopen a superseded historical issue as a shortcut.",
            "",
        ]
    )
    return "\n".join(sections)


def _live_issue_body(issue: dict[str, Any]) -> str:
    phases = ", ".join(f"`{item}`" for item in issue["target_phases"])
    return "\n".join(
        [
            "<!-- Generated by scripts/build_workstream6_issue_backlog_normalization.py. Do not edit manually. -->",
            f"# {issue['normalized_title']}",
            "",
            "> [!CAUTION]",
            "> **CLOSED AS NOT PLANNED AND NOT AUTHORISED TO START.** "
            "This historical issue is retained for provenance only.",
            "",
            "## Normalized classification",
            "",
            "- Classification: `superseded_non_actionable`",
            "- Expected state: `closed`",
            "- Expected state reason: `not_planned`",
            f"- Future implementation phases: {phases}",
            "- Replacement pack: `handoff/future-implementation-issue-pack/future-implementation-issues.md`",
            "- `codex_start_authorized=false`",
            "",
            "## Current issue authority",
            "",
            "- Issue #1 is the only actionable implementation assignment.",
            "- Issue #19 is the only manual pre-launch gate.",
            "- This issue must not be reopened to bypass phase order or exact-phase Founder approval.",
            "",
            "## History and rollback",
            "",
            f"The original title was: **{issue['original_title']}**.",
            "Preserve this history. Reopen only if the normalization itself was factually incorrect.",
            "",
        ]
    )


def build_records() -> tuple[dict[str, Any], dict[str, str], str]:
    source = _load_yaml(SOURCE)
    backlog = (ROOT / source["backlog_file"]).read_text(encoding="utf-8")
    phase_range = source["phase_range"]
    phases = _parse_backlog(backlog, phase_range["first"], phase_range["last"])
    pack_path = f"{source['pack_directory']}/future-implementation-issues.md"
    outputs: dict[str, str] = {pack_path: _pack_body(phases)}

    for issue in source["live_issue_policy"]["normalized_issues"]:
        outputs[issue["body_path"]] = _live_issue_body(issue)

    manifest = {
        "schema_version": 1,
        "pack_id": "WS6.8-FUTURE-IMPLEMENTATION-ISSUE-PACK",
        "status": "blocked_non_authorizing_drafts",
        "backlog_file": source["backlog_file"],
        "phase_drafts": [
            {
                "phase_id": phase["id"],
                "title": phase["title"],
                "depends_on": phase["depends_on"],
                "task_ids": [task["id"] for task in phase["tasks"]],
                "source_path": pack_path,
                "anchor": phase["id"].lower(),
                "draft_only": True,
                "live_issue_created": False,
                "implementation_authorized": False,
            }
            for phase in phases
        ],
        "normalized_live_issues": [
            {
                "issue_number": issue["number"],
                "title": issue["normalized_title"],
                "path": issue["body_path"],
                "expected_state": "closed",
                "expected_state_reason": "not_planned",
            }
            for issue in source["live_issue_policy"]["normalized_issues"]
        ],
        "only_actionable_implementation_issue": 1,
        "only_manual_prelaunch_gate_issue": 19,
        "codex_start_authorized": False,
    }
    outputs[f"{source['pack_directory']}/manifest.json"] = (
        json.dumps(manifest, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    )
    outputs[f"{source['pack_directory']}/README.md"] = "\n".join(
        [
            "# Future implementation issue pack",
            "",
            "> [!CAUTION]",
            "> **NOT AUTHORISED TO START.** This directory contains blocked drafts only.",
            "",
            "- `future-implementation-issues.md` contains twelve phase-scoped drafts for IMP-P1 through IMP-P12.",
            "- `manifest.json` provides the machine-readable phase and dependency map.",
            "- `live-issue-3-superseded.md` through `live-issue-5-superseded.md` are exact closure bodies for historical live issues.",
            "",
            "Issue #1 remains the only actionable implementation assignment. Issue #19 remains the only manual pre-launch gate.",
            "`codex_start_authorized=false`; IMP-P1 through IMP-P12 remain unauthorized.",
            "",
        ]
    )

    contract = {
        **source,
        "generated_from": SOURCE.relative_to(ROOT).as_posix(),
        "future_phases": phases,
        "future_issue_count": len(phases),
        "normalized_live_issue_count": len(
            source["live_issue_policy"]["normalized_issues"]
        ),
        "generated_files": [
            {"path": path, "sha256": _sha256(content)}
            for path, content in sorted(outputs.items())
        ],
    }
    report = "\n".join(
        [
            "# WS6.8 issue and backlog normalization evidence",
            "",
            "<!-- Generated by scripts/build_workstream6_issue_backlog_normalization.py. -->",
            "",
            f"- Base main: `{source['base_main_sha']}`",
            "- Issues #3, #4 and #5 are superseded, closed and non-actionable.",
            "- Issue #1 remains the only actionable implementation assignment.",
            "- Issue #19 remains the only manual pre-launch gate.",
            "- Future blocked issue drafts: `12` (`IMP-P1` through `IMP-P12`).",
            f"- Generated pack files: `{len(outputs)}`.",
            "- Closed defects: `WS6-CONSIST-005`, `WS6-CODEXPREP-007`.",
            "- Remaining blocking defect: `WS6-BLOCK-006`.",
            "- `codex_start_authorized=false`; future implementation phases remain unauthorized.",
            "",
            "Next permitted work package: `WS6.9`.",
            "",
        ]
    )
    return contract, outputs, report


def main() -> None:
    contract, outputs, report = build_records()
    for relative, content in outputs.items():
        path = ROOT / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    CONTRACT.write_text(
        json.dumps(contract, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
        + "\n",
        encoding="utf-8",
    )
    REPORT.write_text(report, encoding="utf-8")
    print(
        "Built WS6.8 issue/backlog normalization: "
        "issues=3, future_drafts=12, next=WS6.9, codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
