from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "workstream6-current-status.yaml"
OUTPUT_PATH = ROOT / "contracts" / "workstream6-current-status.json"
REPORT_PATH = ROOT / "reports" / "workstream6-current-status-evidence.md"


def _load_yaml(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return value


def _canonical(value: object) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"


def _git_blob_sha(path: Path) -> str:
    data = path.read_bytes()
    return hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()


def build_records() -> tuple[dict[str, Any], str]:
    source = _load_yaml(SOURCE_PATH)
    if source.get("work_package_id") != "WS6.3":
        raise ValueError("source must describe WS6.3")
    files = source.get("current_authority_files", [])
    fingerprints = source.get("document_fingerprints", {})
    if not isinstance(files, list) or len(files) != 6:
        raise ValueError("WS6.3 must govern exactly six current authority surfaces")
    if set(files) != set(fingerprints):
        raise ValueError("document fingerprint keys must match current authority files")
    evidence: list[dict[str, str]] = []
    for relative in files:
        path = ROOT / relative
        if not path.is_file():
            raise ValueError(f"missing current authority file: {relative}")
        actual = _git_blob_sha(path)
        if actual != fingerprints[relative]:
            raise ValueError(f"current authority fingerprint drift: {relative}")
        evidence.append({"path": relative, "git_blob_sha": actual})
    boundaries = source["boundaries"]
    if boundaries.get("founder_accountability_preserved") is not True:
        raise ValueError("Founder accountability must be preserved")
    if any(value is not False for key, value in boundaries.items() if key != "founder_accountability_preserved"):
        raise ValueError("all authorization boundaries must remain false")
    contract = {**source,"generated_from":str(SOURCE_PATH.relative_to(ROOT)),"document_evidence":evidence,"document_count":len(evidence),"forbidden_pattern_count":len(source["forbidden_patterns"]),"status":"current_status_documents_reconciled"}
    report = "\n".join([
        "# WS6.3 current-status evidence","","<!-- Generated by scripts/build_workstream6_current_status.py. -->","",
        f"- Base main: `{source['base_main_sha']}`",f"- Current authority surfaces: `{len(evidence)}`",f"- Forbidden stale-state patterns: `{len(source['forbidden_patterns'])}`",f"- Canonical status: {source['canonical_status_phrase']}",
        "- Closed defects: `WS6-BLOCK-003`, `WS6-CONSIST-008`","- Historical WS6.3 remaining blocker: `WS6-BLOCK-006` (closed later by the WS6.16 permanent release).","- Current successor status is represented by the canonical status phrase; WS6.3 package completion fields remain historical.","- `codex_start_authorized=false`; implementation, merge and Phase 1 remain unauthorized.","","## Document fingerprints","",
        *[f"- `{item['path']}` — `{item['git_blob_sha']}`" for item in evidence],"","Historical WS6.3 next permitted work package: `WS6.4`.","",
    ])
    return contract, report


def main() -> None:
    contract, report = build_records()
    OUTPUT_PATH.write_text(_canonical(contract), encoding="utf-8")
    REPORT_PATH.write_text(report, encoding="utf-8")
    print("Built WS6.3 current-status reconciliation: documents=6, closed_defects=2, remaining_blockers=1, next=WS6.4, codex_start_authorized=false.")

if __name__ == "__main__":
    main()
