from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "configs" / "workstream6-configuration-contradictions.yaml"
ENVIRONMENT = ROOT / ".env.example"
OUTPUT = ROOT / "contracts" / "workstream6-configuration-contradictions.json"
REPORT = ROOT / "reports" / "workstream6-configuration-contradictions-evidence.md"


def _load_yaml(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a mapping")
    return value


def _load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain an object")
    return value


def _env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        key, separator, value = line.partition("=")
        if not separator:
            raise ValueError(f"invalid environment line: {raw}")
        if key in values:
            raise ValueError(f"duplicate environment key: {key}")
        values[key] = value
    return values


def _path(value: dict[str, Any], dotted: str) -> Any:
    node: Any = value
    for part in dotted.split("."):
        if not isinstance(node, dict) or part not in node:
            raise ValueError(f"missing contract path: {dotted}")
        node = node[part]
    return node


def build_records() -> tuple[dict[str, Any], str]:
    source = _load_yaml(SOURCE)
    environment = _env(ENVIRONMENT)
    controlling = _load_json(ROOT / source["controlling_contract"])
    observed = {
        name: _path(controlling, dotted)
        for name, dotted in source["contract_paths"].items()
    }
    provider_defaults = {key: environment.get(key) for key in source["paid_provider_keys"]}
    contract = {
        **source,
        "generated_from": SOURCE.relative_to(ROOT).as_posix(),
        "observed_environment_value": environment.get(source["environment_variable"]),
        "observed_provider_key_defaults": provider_defaults,
        "observed_contract_values": observed,
    }
    report = "\n".join([
        "# WS6.7 configuration contradiction evidence",
        "",
        "<!-- Generated by scripts/build_workstream6_configuration_contradictions.py. -->",
        "",
        f"- Base main: `{source['base_main_sha']}`",
        f"- Environment default: `{source['environment_variable']}={contract['observed_environment_value']}`",
        f"- Paid-provider hard cap: `{observed['paid_provider_spend_hard_cap']}`",
        f"- Purchases authorized: `{str(observed['purchases_authorized']).lower()}`",
        f"- Paid services authorized: `{str(observed['paid_services_authorized']).lower()}`",
        "- Provider API-key defaults are blank.",
        "- Closed defect: `WS6-CONSIST-004`.",
        "- Remaining blocking defect: `WS6-BLOCK-006`.",
        "- `codex_start_authorized=false`; IMP-P0, merge, runtime, production and IMP-P1 remain unauthorized.",
        "",
        "Next permitted work package: `WS6.8`.",
        "",
    ])
    return contract, report


def main() -> None:
    contract, report = build_records()
    OUTPUT.write_text(json.dumps(contract, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")
    REPORT.write_text(report, encoding="utf-8")
    print("Built WS6.7 configuration contradiction evidence: zero-spend defaults, next=WS6.8.")


if __name__ == "__main__":
    main()
