from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "configs/workstream6-final-workflow.yaml"
OUT = ROOT / "contracts/workstream6-final-workflow.json"
DOC = ROOT / "docs/67-WS6-15-FINAL-WORKFLOW.md"
REPORT = ROOT / "reports/workstream6-final-workflow-evidence.md"


def load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def canon(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False) + "\n"


def build_records() -> tuple[dict[str, Any], str, str]:
    source = load(SRC)
    if source.get("work_package_id") != "WS6.15":
        raise ValueError("WS6.15 source has wrong work package")
    contract = {
        **source,
        "generated_from": SRC.relative_to(ROOT).as_posix(),
        "source_sha256": hashlib.sha256(SRC.read_bytes()).hexdigest(),
        "automatic_trigger_count": len(source["activation"]["automatic_triggers"]),
        "remaining_defect_count": len(source["remaining_defects"]),
    }
    doc = "\n".join([
        "# WS6.15 — Final workflow",
        "",
        "> [!CAUTION]",
        "> **WORKFLOW ACTIVATION IS NOT CODEX AUTHORIZATION.** WS6.15 activates the exact final check while keeping the permanent release, manual gates, permit, IMP-P0 implementation and merge authority false.",
        "",
        f"- Exact predecessor: `{source['predecessor']['head_sha']}` (WS6.14 / PR #55).",
        f"- Current integrated main remains `{source['main_integration']['integrated_main_sha']}` through `{source['main_integration']['integrated_through']}`.",
        f"- Final check: `{source['canonical_identity']['job_name']}`.",
        "- Automatic triggers: pull requests, pushes to `main`, and manual dispatch.",
        "- Exact WS6.15 activation PR may pass without a permanent release only when its branch, base branch and base SHA all match the governed exception and the permanent release is absent.",
        "- Every other run requires `scripts/require_workstream6_final_reconciliation.py` to pass.",
        "- After WS6.15 integration, `main` therefore fails closed until WS6.16 creates and validates the permanent release.",
        "- Hosted branch protection remains a separate issue #19 manual gate.",
        "- `codex_start_authorized=false`.",
        "",
        "## Remaining defects",
        "",
        *[f"- `{item}`" for item in source["remaining_defects"]],
        "",
        "## Next package",
        "",
        "`WS6.16` — permanent post-merge release and final evidence reconciliation.",
    ])
    report = "\n".join([
        "# WS6.15 final workflow evidence",
        "",
        "<!-- Generated by scripts/build_workstream6_final_workflow.py. -->",
        "",
        f"- Predecessor head: `{source['predecessor']['head_sha']}`.",
        f"- Exact final check: `{source['canonical_identity']['job_name']}`.",
        f"- Automatic triggers: `{len(source['activation']['automatic_triggers'])}`.",
        "- Activation state: `active_fail_closed_pending_permanent_release`.",
        "- Permanent release complete: `false`.",
        "- Manual launch gates complete: `false`.",
        "- `codex_start_authorized=false`.",
        "- Next permitted work package: `WS6.16`.",
    ])
    return contract, doc, report


def main() -> None:
    contract, doc, report = build_records()
    for path, text in ((OUT, canon(contract)), (DOC, doc + "\n"), (REPORT, report + "\n")):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    print(
        "Built WS6.15 final workflow: triggers=3, activation=active_fail_closed_pending_permanent_release, "
        "remaining_defects=3, next=WS6.16, codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
