from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "current-operational-state.yaml"
OUTPUT_PATH = ROOT / "repository" / "current-operational-state.json"
REPORT_PATH = ROOT / "reports" / "pcfa02-current-operational-state-evidence.md"
POSTURE_PATH = ROOT / "repository" / "repository-visibility-and-licence-posture.json"


def _load_source() -> dict[str, Any]:
    value = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("current operational-state source must contain a mapping")
    return value


def _canonical(value: object) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"


def _digest_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build_records() -> tuple[dict[str, Any], str]:
    source = _load_source()
    if source.get("projection_id") != "CURRENT-OPERATIONAL-STATE":
        raise ValueError("current operational-state projection identity drifted")
    if source.get("introduced_by") != "PCFA-02":
        raise ValueError("current operational-state introduction package drifted")
    if not POSTURE_PATH.is_file():
        raise ValueError("current repository visibility/licence posture record is missing")

    state = dict(source)
    snapshots = []
    for item in source.get("historical_package_snapshots", []):
        if not isinstance(item, dict):
            raise ValueError("historical package snapshot entries must be mappings")
        snapshots.append(
            {
                "path": item["path"],
                "package": item["package"],
                "classification": item["classification"],
            }
        )
    state["historical_package_snapshots"] = snapshots
    state["generated_from"] = str(SOURCE_PATH.relative_to(ROOT))
    authority = dict(state["current_authority"])
    authority["repository_posture_sha256"] = _digest_file(POSTURE_PATH)
    state["current_authority"] = authority

    manual = state["manual_launch_gates"]
    boundaries = state["boundaries"]
    report = "\n".join(
        [
            "# PCFA-02 current operational-state evidence",
            "",
            "<!-- Generated by scripts/build_pcfa02_current_operational_state.py. -->",
            "",
            f"- Projection: `{state['projection_id']}`",
            f"- Introduced by: `{state['introduced_by']}`",
            f"- Current authority entries: `{len(authority)}`",
            f"- Historical/corrective snapshots: `{len(snapshots)}`",
            f"- Manual launch gates committed false: `{sum(value is False for value in manual.values())}`",
            f"- Authorization boundaries: `{len(boundaries)}`",
            "- Sole live machine readiness projection: `repository/current-operational-state.json`",
            "- Current repository posture: `repository/repository-visibility-and-licence-posture.json`",
            f"- Repository posture SHA-256: `{authority['repository_posture_sha256']}`",
            "- Current machine handoff: `handoff/codex-phase0-current-handoff.json`",
            "- Current Issue #1 body: `handoff/codex-phase0-current-issue.md`",
            "- Current Issue #19 body: `handoff/codex-phase0-current-hosted-controls-issue.md`",
            "- WS6.2/WS6.3/WS6.4/WS6.13 embedded readiness and licence state remain retained package-time evidence only.",
            "- Permanent WS6.16 release remains immutable evidence, not the current launch SHA.",
            "- `codex_start_authorized=false`; merge, IMP-P1, runtime and external actions remain denied.",
            "",
        ]
    )
    return state, report


def main() -> None:
    state, report = build_records()
    OUTPUT_PATH.write_text(_canonical(state), encoding="utf-8")
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(
        "Built PCFA-02 current operational state: "
        f"historical_snapshots={len(state['historical_package_snapshots'])}, "
        "repository_posture_bound=true, manual_gates=false, codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
