from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "workstream6-phase-namespace.yaml"
OUTPUT_PATH = ROOT / "contracts" / "workstream6-phase-namespace.json"
REPORT_PATH = ROOT / "reports" / "workstream6-phase-namespace-evidence.md"


def _load_source() -> dict[str, Any]:
    value = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("WS6.5 source must contain a mapping")
    if value.get("work_package_id") != "WS6.5":
        raise ValueError("WS6.5 source has the wrong work package")
    return value


def _canonical(value: object) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"


def _git_blob_sha(path: Path) -> str:
    data = path.read_bytes()
    return hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()


def build_records() -> tuple[dict[str, Any], str]:
    source = _load_source()
    namespaces = source.get("namespaces")
    aliases = source.get("legacy_aliases")
    surfaces = source.get("normalization_surfaces")
    if not isinstance(namespaces, list) or len(namespaces) != 4:
        raise ValueError("WS6.5 must define exactly four namespaces")
    if not isinstance(aliases, list) or len(aliases) != 14:
        raise ValueError("WS6.5 must define exactly fourteen legacy aliases")
    if not isinstance(surfaces, list) or len(surfaces) != 9:
        raise ValueError("WS6.5 must govern exactly nine normalization surfaces")
    evidence: list[dict[str, Any]] = []
    for relative in surfaces:
        path = ROOT / str(relative)
        if not path.is_file():
            raise ValueError(f"missing normalization surface: {relative}")
        evidence.append({"path": str(relative), "bytes": path.stat().st_size, "git_blob_sha": _git_blob_sha(path)})
    namespace_id_count = sum(len(item.get("canonical_ids", [])) for item in namespaces if isinstance(item, dict))
    contract = {**source, "generated_from": str(SOURCE_PATH.relative_to(ROOT)), "surface_evidence": evidence, "surface_count": len(evidence), "namespace_id_count": namespace_id_count, "legacy_alias_count": len(aliases)}
    report = "\n".join([
        "# WS6.5 phase namespace normalization", "",
        "<!-- Generated by scripts/build_workstream6_phase_namespace.py. -->", "",
        f"- Base main: `{source['base_main_sha']}`",
        f"- Canonical namespace IDs: `{namespace_id_count}`",
        f"- Legacy display aliases: `{len(aliases)}`",
        f"- Normalized current-authority surfaces: `{len(evidence)}`",
        "- Canonical families: `CF-P1–7`, `PCR-01–10`, `WS-4`, `WS-5`, `WS6.x`, `IMP-P0–12`.",
        "- Stable filenames, task IDs, branch names and verifier keys remain compatibility identifiers only.",
        "- Founder approval intent was recorded, but it is not exact-SHA launch authorization.",
        "- Closed defect: `WS6-CONSIST-002`.",
        "- Remaining blocking defect: `WS6-BLOCK-006`.",
        "- `codex_start_authorized=false`; IMP-P0, merge and IMP-P1 remain unauthorized.", "",
        "## Surface fingerprints", "",
        *[f"- `{item['path']}` — `{item['git_blob_sha']}` ({item['bytes']} bytes)" for item in evidence], "",
        "Next permitted work package: `WS6.6`.", "",
    ])
    return contract, report


def main() -> None:
    contract, report = build_records()
    OUTPUT_PATH.write_text(_canonical(contract), encoding="utf-8")
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(
        "Built WS6.5 phase namespace: "
        f"namespaces=4, canonical_ids={contract['namespace_id_count']}, "
        f"surfaces={contract['surface_count']}, aliases={contract['legacy_alias_count']}, "
        "next=WS6.6, codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
