from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "workstream6-required-workflow-identity.yaml"
OUTPUT_PATH = ROOT / "contracts" / "workstream6-required-workflow-identity.json"
REPORT_PATH = ROOT / "reports" / "workstream6-required-workflow-identity-evidence.md"


def _load_source() -> dict[str, Any]:
    value = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("WS6.6 source must contain a mapping")
    if value.get("work_package_id") != "WS6.6":
        raise ValueError("WS6.6 source has the wrong work package")
    return value


def _canonical(value: object) -> str:
    return json.dumps(
        value,
        sort_keys=True,
        ensure_ascii=False,
        separators=(",", ":"),
    ) + "\n"


def _blob(path: Path) -> dict[str, Any]:
    data = path.read_bytes()
    digest = hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()
    return {
        "path": path.relative_to(ROOT).as_posix(),
        "bytes": len(data),
        "git_blob_sha": digest,
    }


def _parse_workflow(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    workflow_name = ""
    current_job = ""
    jobs: dict[str, str] = {}
    triggers: list[str] = []
    in_jobs = False

    for line in text.splitlines():
        if line.startswith("name: ") and not workflow_name:
            workflow_name = line.split(":", 1)[1].strip()
        match = re.match(r"^  (push|pull_request|workflow_dispatch|workflow_call):", line)
        if match:
            triggers.append(match.group(1))
        if line == "jobs:":
            in_jobs = True
            continue
        if not in_jobs:
            continue
        job_match = re.match(r"^  ([A-Za-z0-9_-]+):\s*$", line)
        if job_match:
            current_job = job_match.group(1)
            jobs[current_job] = ""
            continue
        name_match = re.match(r"^    name:\s*(.+)$", line)
        if name_match and current_job:
            jobs[current_job] = name_match.group(1).strip()

    return {
        "workflow_name": workflow_name,
        "triggers": triggers,
        "jobs": jobs,
        "contains_exit_1": "exit 1" in text,
        "contains_ws615": "WS6.15" in text,
    }


def build_records() -> tuple[dict[str, Any], str]:
    source = _load_source()
    identity = source["canonical_identity"]
    workflow = ROOT / identity["workflow_file"]
    package = ROOT / ".github/workflows/workstream6-required-workflow-identity.yml"
    if not workflow.is_file() or not package.is_file():
        raise ValueError("WS6.6 workflow files are missing")

    parsed = _parse_workflow(workflow)
    authority: list[dict[str, Any]] = []
    for relative in source["authority_surfaces"]:
        path = ROOT / relative
        if not path.is_file():
            raise ValueError(f"missing authority surface: {relative}")
        authority.append(_blob(path))

    contract = {
        **source,
        "generated_from": SOURCE_PATH.relative_to(ROOT).as_posix(),
        "workflow_evidence": [_blob(workflow), _blob(package)],
        "canonical_workflow_observed": parsed,
        "authority_evidence": authority,
        "authority_surface_count": len(authority),
    }
    report = "\n".join(
        [
            "# WS6.6 required workflow identity evidence",
            "",
            "<!-- Generated by scripts/build_workstream6_required_workflow_identity.py. -->",
            "",
            f"- Base main: `{source['base_main_sha']}`",
            f"- Canonical workflow: `{identity['workflow_file']}`",
            f"- Canonical workflow name: `{identity['workflow_name']}`",
            f"- Canonical job key: `{identity['job_key']}`",
            f"- Canonical required check: `{identity['job_name']}`",
            "- Reservation state: `reserved_fail_closed`.",
            "- Automatic triggers enabled: `false`.",
            "- Hosted branch protection configured: `false`.",
            "- Activation package: `WS6.15`; permanent release package: `WS6.16`.",
            f"- Current authority surfaces: `{len(authority)}`",
            "- Closed defect: `WS6-CONSIST-003`.",
            "- Remaining blocking defect: `WS6-BLOCK-006`.",
            "- `codex_start_authorized=false`; IMP-P0, merge and IMP-P1 remain unauthorized.",
            "",
            "## Workflow fingerprints",
            "",
            *[
                f"- `{item['path']}` — `{item['git_blob_sha']}` ({item['bytes']} bytes)"
                for item in contract["workflow_evidence"]
            ],
            "",
            "## Authority fingerprints",
            "",
            *[
                f"- `{item['path']}` — `{item['git_blob_sha']}` ({item['bytes']} bytes)"
                for item in authority
            ],
            "",
            "Next permitted work package: `WS6.7`.",
            "",
        ]
    )
    return contract, report


def main() -> None:
    contract, report = build_records()
    OUTPUT_PATH.write_text(_canonical(contract), encoding="utf-8")
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(
        "Built WS6.6 required workflow identity: "
        f"workflows={len(contract['workflow_evidence'])}, "
        f"authority_surfaces={contract['authority_surface_count']}, "
        "next=WS6.7, codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
