from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "workstream6-final-launch-control.yaml"
LAUNCH_CONTRACT_PATH = ROOT / "contracts" / "codex-phase0-launch-control.json"
FINAL_ISSUE_PATH = ROOT / "handoff" / "codex-phase0-issue-final.md"
OUTPUT_PATH = ROOT / "contracts" / "workstream6-final-launch-control.json"
REPORT_PATH = ROOT / "reports" / "workstream6-final-launch-control-evidence.md"


def _load_yaml(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return value


def _load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def _canonical_json(value: object) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build_records() -> tuple[dict[str, Any], str]:
    source = _load_yaml(SOURCE_PATH)
    launch = _load_json(LAUNCH_CONTRACT_PATH)
    if source.get("work_package_id") != "WS6.2":
        raise ValueError("source must describe WS6.2")
    if launch.get("work_package_id") != "WS6.2":
        raise ValueError("controlling launch contract is not WS6.2")
    if launch.get("closed_defects") != source.get("closed_defects"):
        raise ValueError("launch contract defect closure does not match WS6.2")
    if launch.get("remaining_blocking_defects") != source.get("remaining_blocking_defects"):
        raise ValueError("remaining blocker set does not match WS6.2")
    boundaries = source["boundaries"]
    if boundaries.get("founder_accountability_preserved") is not True:
        raise ValueError("Founder accountability must be preserved")
    if any(value is not False for key, value in boundaries.items() if key != "founder_accountability_preserved"):
        raise ValueError("all authorization boundaries must remain false")

    contract = {
        **source,
        "generated_from": str(SOURCE_PATH.relative_to(ROOT)),
        "evidence": {
            "launch_contract_path": str(LAUNCH_CONTRACT_PATH.relative_to(ROOT)),
            "launch_contract_sha256": _digest(LAUNCH_CONTRACT_PATH),
            "final_issue_path": str(FINAL_ISSUE_PATH.relative_to(ROOT)),
            "final_issue_sha256": _digest(FINAL_ISSUE_PATH),
            "historical_issue_sha256": launch["historical_authority"]["workstream5_issue_body"]["sha256"],
            "required_status_check": launch["required_status_check"]["job_name"],
            "read_order_count": launch["launch_protocol_registry"]["read_order_count"],
            "preflight_command_count": launch["launch_protocol_registry"]["preflight_command_count"],
            "launch_self_test_mutation_minimum": 39,
            "package_mutation_minimum": 20,
        },
        "status": "final_launch_control_reconciled",
    }
    report = "\n".join([
        "# WS6.2 final launch-control evidence",
        "",
        "<!-- Generated by scripts/build_workstream6_final_launch_control.py. -->",
        "",
        f"- Base main: `{source['base_main_sha']}`",
        f"- Controlling launch contract: `{contract['evidence']['launch_contract_path']}`",
        f"- Launch-contract SHA-256: `{contract['evidence']['launch_contract_sha256']}`",
        f"- Final canonical issue: `{contract['evidence']['final_issue_path']}`",
        f"- Final issue SHA-256: `{contract['evidence']['final_issue_sha256']}`",
        f"- Historical Workstream 5 issue SHA-256: `{contract['evidence']['historical_issue_sha256']}`",
        f"- Required status check: `{contract['evidence']['required_status_check']}`",
        "- Closed defects: `WS6-BLOCK-004`, `WS6-BLOCK-005`",
        "- Remaining blockers: `WS6-BLOCK-003`, `WS6-BLOCK-006`",
        "- Final Workstream 6 release, hosted controls, clean macOS, Founder approval and permit remain pending.",
        "- `codex_start_authorized=false`; implementation, merge and Phase 1 remain unauthorized.",
        "",
        "Next permitted work package: `WS6.3`.",
        "",
    ])
    return contract, report


def main() -> None:
    contract, report = build_records()
    OUTPUT_PATH.write_text(_canonical_json(contract), encoding="utf-8")
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(
        "Built WS6.2 reconciliation record: closed_defects=2, remaining_blockers=2, "
        "next=WS6.3, codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
