from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "workstream6-handoff-reconciliation.yaml"
CONTRACT_PATH = ROOT / "contracts" / "workstream6-handoff-reconciliation.json"
REPORT_PATH = ROOT / "reports" / "workstream6-handoff-reconciliation-evidence.md"


def _load_yaml(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return value


def _canonical_json(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n"


def build_records() -> tuple[dict[str, Any], str]:
    source = _load_yaml(SOURCE_PATH)
    if source.get("work_package_id") != "WS6.1":
        raise ValueError("source must describe WS6.1")
    if source.get("base_main_sha") != "5c80cea82aa663cbe0a690e3f8f02504d121bea1":
        raise ValueError("WS6.1 must start from the exact WS6.0 merge")
    if source.get("closed_defects") != ["WS6-BLOCK-001", "WS6-BLOCK-002"]:
        raise ValueError("WS6.1 must close exactly the two handoff blockers")
    if source.get("remaining_blocking_defects") != [
        "WS6-BLOCK-003",
        "WS6-BLOCK-004",
        "WS6-BLOCK-005",
        "WS6-BLOCK-006",
    ]:
        raise ValueError("remaining blockers are incorrect")
    completion = source.get("completion", {})
    if completion.get("ws60_complete") is not True:
        raise ValueError("WS6.0 must remain complete")
    if completion.get("ws61_complete") is not True:
        raise ValueError("WS6.1 must be complete in its generated package")
    if completion.get("all_blocking_defects_closed") is not False:
        raise ValueError("later blocking defects must remain open")
    if completion.get("next_permitted_work_package") != "WS6.2":
        raise ValueError("WS6.2 must be next")
    boundaries = source.get("boundaries", {})
    if boundaries.get("founder_accountability_preserved") is not True:
        raise ValueError("Founder accountability must remain preserved")
    for key, value in boundaries.items():
        if key != "founder_accountability_preserved" and value is not False:
            raise ValueError(f"boundary {key} must remain false")

    contract = dict(source)
    contract["generated_from"] = str(SOURCE_PATH.relative_to(ROOT))
    contract["evidence_report"] = str(REPORT_PATH.relative_to(ROOT))

    reconciliation = source["reconciliation"]
    report = "\n".join(
        [
            "# WS6.1 controlling machine handoff reconciliation evidence",
            "",
            "<!-- Generated by scripts/build_workstream6_handoff_reconciliation.py. -->",
            "",
            "## Base",
            "",
            f"- Exact `main` base: `{source['base_main_sha']}`",
            "- Work package: `WS6.1`",
            f"- Status: `{source['status']}`",
            "",
            "## Repairs",
            "",
            "- Closed `WS6-BLOCK-001`: the handoff now includes PCR-10, Workstreams 4–6 and the final permit prerequisite.",
            "- Closed `WS6-BLOCK-002`: the validator rejects stale activation, read-order, prerequisite, command and P0.3 scopes.",
            f"- Prerequisites: {reconciliation['prerequisite_record_count']} records.",
            f"- Read order: {reconciliation['read_order_count']} paths.",
            f"- Required commands: {reconciliation['required_command_count']} commands.",
            f"- Activation conditions: {reconciliation['activation_condition_count']} conditions.",
            "",
            "## Fail-closed boundary",
            "",
            "The final Workstream 6 gate, hosted controls, clean macOS evidence, Founder approval and a valid single-use launch permit remain incomplete. `codex_start_authorized=false`.",
            "",
            "Next permitted work package: `WS6.2`.",
            "",
        ]
    )
    return contract, report


def main() -> None:
    contract, report = build_records()
    CONTRACT_PATH.write_text(_canonical_json(contract), encoding="utf-8")
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(
        "Built WS6.1 handoff reconciliation: "
        f"closed_defects={len(contract['closed_defects'])}, "
        f"remaining_blockers={len(contract['remaining_blocking_defects'])}, "
        "codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
