from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "pcfa04-product-scope-implementation-addendum.yaml"
OUTPUT_PATH = ROOT / "repository" / "pcfa04-product-scope-implementation-addendum.json"
REPORT_PATH = ROOT / "reports" / "pcfa04-product-scope-implementation-addendum-evidence.md"


def _load_source() -> dict[str, Any]:
    value = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("PCFA-04 product-scope source must contain a mapping")
    return value


def _canonical(value: object) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"


def build_records() -> tuple[dict[str, Any], str]:
    source = _load_source()
    if source.get("work_package_id") != "PCFA-04":
        raise ValueError("PCFA-04 product-scope identity drifted")
    if source.get("addendum_id") != "PRODUCT-SCOPE-IMPLEMENTATION-ADDENDUM":
        raise ValueError("PCFA-04 addendum identity drifted")

    record = dict(source)
    record["generated_from"] = str(SOURCE_PATH.relative_to(ROOT))
    areas = record.get("product_areas", [])
    requirements = record.get("requirements", [])
    cq = [item for item in requirements if isinstance(item, dict) and str(item.get("id", "")).startswith("CQ-")]
    phases = sorted(
        {
            phase
            for area in areas
            if isinstance(area, dict)
            for phase in area.get("owning_imp_phases", [])
        }
    )
    report = "\n".join(
        [
            "# PCFA-04 product-scope implementation addendum evidence",
            "",
            "<!-- Generated by scripts/build_pcfa04_product_scope_addendum.py. -->",
            "",
            f"- Work package: `{record['work_package_id']}`",
            f"- Addendum: `{record['addendum_id']}`",
            f"- Product areas: `{len(areas)}`",
            f"- Requirements: `{len(requirements)}`",
            f"- Consulting Craft requirements: `{len(cq)}`",
            f"- Owning IMP phases represented: `{len(phases)}`",
            "- Status for every requirement: `planned_not_implemented`",
            "- Product runtime implemented: `false`",
            "- PCFA-05 MVCL contract remains required: `true`",
            "- PCFA-07 global obligation/test reconciliation remains required: `true`",
            "- `codex_start_authorized=false`; implementation, merge, runtime and external-action boundaries remain denied.",
            "",
        ]
    )
    return record, report


def main() -> None:
    record, report = build_records()
    OUTPUT_PATH.write_text(_canonical(record), encoding="utf-8")
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(
        "Built PCFA-04 product-scope implementation addendum: "
        f"areas={len(record['product_areas'])}, requirements={len(record['requirements'])}, "
        "consulting_craft=15, planned_not_implemented=true, codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
