from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "pcfa05-minimum-valuable-consulting-loop.yaml"
OUTPUT_PATH = ROOT / "repository" / "pcfa05-minimum-valuable-consulting-loop.json"
REPORT_PATH = ROOT / "reports" / "pcfa05-minimum-valuable-consulting-loop-evidence.md"


def _load_source() -> dict[str, Any]:
    value = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("PCFA-05 MVCL source must contain a mapping")
    return value


def _canonical(value: object) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"


def build_records() -> tuple[dict[str, Any], str]:
    source = _load_source()
    if source.get("work_package_id") != "PCFA-05":
        raise ValueError("PCFA-05 MVCL identity drifted")
    if source.get("contract_id") != "MINIMUM-VALUABLE-CONSULTING-LOOP":
        raise ValueError("PCFA-05 MVCL contract identity drifted")

    record = dict(source)
    record["generated_from"] = str(SOURCE_PATH.relative_to(ROOT))
    stages = record.get("stages", [])
    invariants = record.get("loop_invariants", [])
    negative_cases = record.get("negative_cases", [])
    interrupts = record.get("founder_interrupts", [])
    phases = sorted(
        {
            phase
            for stage in stages
            if isinstance(stage, dict)
            for phase in stage.get("owning_imp_phases", [])
        }
    )
    report = "\n".join(
        [
            "# PCFA-05 Minimum Valuable Consulting Loop evidence",
            "",
            "<!-- Generated by scripts/build_pcfa05_mvcl.py. -->",
            "",
            f"- Work package: `{record['work_package_id']}`",
            f"- Contract: `{record['contract_id']}`",
            f"- Consulting-loop stages: `{len(stages)}`",
            f"- Loop invariants: `{len(invariants)}`",
            f"- Founder interrupt classes: `{len(interrupts)}`",
            f"- Negative-path cases: `{len(negative_cases)}`",
            f"- Owning IMP phases represented: `{len(phases)}`",
            "- Status for every stage: `planned_not_implemented`",
            "- Product/workflow runtime implemented: `false`",
            "- PCFA-07 global obligation/test reconciliation remains required: `true`",
            "- PCFA-08 final cross-authority acceptance remains required: `true`",
            "- `codex_start_authorized=false`; implementation, merge, runtime and external-action boundaries remain denied.",
            "",
        ]
    )
    return record, report


def main() -> None:
    record, report = build_records()
    OUTPUT_PATH.write_text(_canonical(record), encoding="utf-8")
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(
        "Built PCFA-05 Minimum Valuable Consulting Loop: "
        f"stages={len(record['stages'])}, invariants={len(record['loop_invariants'])}, "
        f"founder_interrupts={len(record['founder_interrupts'])}, "
        f"negative_cases={len(record['negative_cases'])}, planned_not_implemented=true, "
        "codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
