from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "pre-codex-readiness.yaml"
PCR09_CONTRACT_PATH = ROOT / "contracts" / "codex-phase0-issue.json"
HANDOFF_PATH = ROOT / "handoff" / "codex-phase0-handoff.json"
PCR09_BODY_PATH = ROOT / "handoff" / "codex-phase0-issue.md"
CONTRACT_PATH = ROOT / "contracts" / "pre-codex-readiness.json"
FINAL_BODY_PATH = ROOT / "handoff" / "codex-phase0-issue-pcr10.md"


def _load_yaml(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return value


def _load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def _canonical_json(value: object) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _insert_after(lines: list[str], anchor: str, new_lines: list[str]) -> None:
    if anchor not in lines:
        raise ValueError(f"Issue-body anchor missing: {anchor}")
    index = lines.index(anchor)
    lines[index + 1:index + 1] = new_lines


def _insert_before(lines: list[str], anchor: str, new_lines: list[str]) -> None:
    if anchor not in lines:
        raise ValueError(f"Issue-body anchor missing: {anchor}")
    index = lines.index(anchor)
    lines[index:index] = new_lines


def build_final_issue_body(source: dict[str, Any]) -> str:
    body = PCR09_BODY_PATH.read_text(encoding="utf-8")
    lines = body.splitlines()
    if not lines or "build_pcr09_codex_issue.py" not in lines[0]:
        raise ValueError("PCR-09 generated issue body header is missing")
    lines[0] = "<!-- Generated by scripts/build_pcr10_pre_codex_readiness.py. Do not edit manually. -->"

    _insert_after(
        lines,
        "- `handoff/codex-phase0-handoff.json` is the machine-readable Phase 0 execution contract.",
        [
            "- `contracts/pre-codex-readiness.json` is the final pre-start release and quality gate and extends, but does not replace, the Phase 0 execution task graph.",
            "- `handoff/codex-phase0-issue-pcr10.md` is the final generated issue body after PCR-10; the PCR-09 body remains retained as predecessor evidence.",
        ],
    )
    _insert_after(lines, "- [ ] `pcr09_merged_to_main`", ["- [ ] `pcr10_merged_to_main`"])
    _insert_after(
        lines,
        "26. `handoff/codex-phase0-issue.md`",
        [
            "27. `docs/49-PCR-10-PRE-CODEX-RELEASE-AND-QUALITY-ACCEPTANCE.md`",
            "28. `contracts/pre-codex-readiness.json`",
            "29. `handoff/codex-phase0-issue-pcr10.md`",
        ],
    )
    _insert_after(
        lines,
        "python scripts/build_pcr04_codex_handoff.py",
        ["python scripts/build_pcr10_pre_codex_readiness.py"],
    )
    _insert_after(
        lines,
        "python scripts/validate_pcr04_codex_handoff.py",
        ["python scripts/validate_pcr10_pre_codex_readiness.py"],
    )

    quality_section = [
        "## PCR-10 quality and operating acceptance",
        "",
        "Phase 0 must establish the implementation hooks, commands and evidence required by `contracts/pre-codex-readiness.json`. Later product phases must satisfy the registered Founder-experience and deliverable-quality obligations without weakening the Phase 0 boundary.",
        "The only next permitted implementation phase after every activation gate is satisfied is Codex Phase 0 only.",
        "",
        "### Developer experience",
        "",
        "- Provide root-level `doctor`, `bootstrap`, `up`, `down`, `restart`, `health`, `test`, `lint`, `format`, `scan`, `reset-synthetic`, `backup`, `restore`, `clean` and `support-bundle` commands.",
        "- Detect unsupported versions and port conflicts before startup, keep cleanup path-safe, and redact all credentials and sensitive values.",
        "",
        "### Founder experience",
        "",
        "- Keep recommendation, authorization and execution consequences distinct.",
        "- Expose decision deadlines, reversibility, evidence drill-through and explicit waiting, blocked, retrying, failed, stale and complete states.",
        "- Prevent any client or prospect sending from an unauthorized state.",
        "",
        "### Deliverable quality",
        "",
        "- Resolve 100 percent of material citations, permit zero unsupported material claims, and reconcile 100 percent of material numbers across formats.",
        "- Office outputs must open without repair warnings, remain editable, preserve citations, pass accessibility checks and meet visual-regression requirements.",
        "",
        "### Operational quality",
        "",
        "- Provide structured correlation IDs, error and retry taxonomy, health/readiness/liveness checks, privacy-safe tracing, SBOM evidence, backup/restore and rollback drills.",
        "- Record cost, usage, latency, Founder corrections, overrides, editing time, human time saved and quality per cost as implementation phases make those signals available.",
        "",
    ]
    _insert_before(lines, "## Required method", quality_section)

    _insert_after(
        lines,
        "- Exact rollback and cleanup commands.",
        [
            "- PCR-10 readiness-contract validation and the exact final issue-body digest.",
            "- Root command inventory, redacted support-bundle evidence, backup/restore drill and release-quality acceptance mapping.",
        ],
    )

    gate_index = lines.index("## Phase 0 gate")
    for index in range(gate_index + 1, min(gate_index + 8, len(lines))):
        if lines[index].startswith("Completion means"):
            lines[index] = (
                "Completion means a draft pull request and local demonstration packet are ready for Founder review, "
                "the applicable Phase 0 obligations in the PCR-10 readiness contract have evidence, and no critical "
                "or high defect remains. No substantive product workflow is required. Codex must not merge, activate "
                "a runtime, enable real client data, or begin Phase 1."
            )
            break
    else:
        raise ValueError("Phase 0 gate paragraph is missing")

    supersession_index = lines.index("## Supersession")
    for index in range(supersession_index + 1, min(supersession_index + 8, len(lines))):
        if lines[index].startswith("This is the single canonical Codex Phase 0 issue"):
            lines[index] = (
                "This remains the single canonical Codex Phase 0 issue. PCR-10 owns the final pre-start gate and "
                "generated issue body; the PCR-09 body remains retained predecessor evidence. Issue #2 remains "
                "superseded as a duplicate and is not an additional workstream or authority source."
            )
            break
    else:
        raise ValueError("Supersession paragraph is missing")

    return "\n".join(lines).rstrip() + "\n"


def build_contract() -> tuple[dict[str, Any], str]:
    source = _load_yaml(SOURCE_PATH)
    pcr09 = _load_json(PCR09_CONTRACT_PATH)
    handoff = _load_json(HANDOFF_PATH)
    final_body = build_final_issue_body(source)
    activation = source["activation_conditions"]
    prior_activation = pcr09["handoff_snapshot"]["activation_conditions"]
    expected_activation = list(prior_activation)
    expected_activation.insert(
        expected_activation.index("github_hosted_controls_in_issue_19_verified"),
        "pcr10_merged_to_main",
    )

    criteria_ids: list[str] = []
    for section in (
        "developer_experience",
        "founder_experience",
        "operational_quality",
        "cross_cutting",
    ):
        criteria_ids.extend(
            item["id"] for item in source[section]["acceptance_criteria"]
        )
    for section in ("evidence", "quantitative"):
        criteria_ids.extend(
            item["id"] for item in source["output_quality"][section]
        )

    checks = {
        "pcr09_contract_present": PCR09_CONTRACT_PATH.is_file(),
        "pcr04_handoff_present": HANDOFF_PATH.is_file(),
        "pcr09_issue_body_present": PCR09_BODY_PATH.is_file(),
        "pcr10_activation_is_exact_extension": activation == expected_activation,
        "pcr09_codex_start_remains_false": (
            pcr09["boundaries"]["codex_start_authorized"] is False
        ),
        "handoff_codex_start_remains_false": (
            handoff["readiness_snapshot"]["codex_start_authorized"] is False
        ),
        "all_pcr10_authorization_boundaries_denied": all(
            value is False
            for key, value in source["boundaries"].items()
            if key != "founder_accountability_preserved"
        ),
        "founder_accountability_preserved": (
            source["boundaries"]["founder_accountability_preserved"] is True
        ),
        "quality_criteria_ids_unique": len(criteria_ids) == len(set(criteria_ids)),
        "critical_or_high_defects_allowed_is_zero": (
            source["release_integrity"]["critical_or_high_defects_allowed"] == 0
        ),
    }

    contract = {
        **{
            key: source[key]
            for key in (
                "schema_version",
                "contract_id",
                "phase_id",
                "title",
                "repository",
                "canonical_branch",
                "status",
                "authority",
                "activation_conditions",
                "prior_phase_records",
                "release_integrity",
                "developer_experience",
                "founder_experience",
                "output_quality",
                "operational_quality",
                "learning_measurement",
                "cross_cutting",
                "implementation_mapping",
                "issue_extension",
                "boundaries",
            )
        },
        "generated_from": str(SOURCE_PATH.relative_to(ROOT)),
        "generated_issue": {
            "body_path": str(FINAL_BODY_PATH.relative_to(ROOT)),
            "body_sha256": _sha256(final_body),
            "body_line_count": len(final_body.splitlines()),
            "body_character_count": len(final_body),
            "github_issue_sync_verified": False,
        },
        "readiness_snapshot": {
            "checks": checks,
            "local_prerequisites_passed": all(checks.values()),
            "chat_first_scope_complete": all(checks.values()),
            "release_integration_complete": False,
            "pcr10_merge_required": True,
            "issue_19_hosted_controls_verified": False,
            "clean_macos_environment_verified": False,
            "explicit_founder_phase_0_approval_received": False,
            "codex_start_authorized": False,
            "next_permitted_phase_after_all_gates": "Codex Phase 0 only",
        },
        "quality_registry": {
            "criterion_ids": criteria_ids,
            "criterion_count": len(criteria_ids),
            "artifact_surface_count": len(
                source["output_quality"]["artifact_surfaces"]
            ),
            "developer_command_count": len(
                source["developer_experience"]["phase0_required_commands"]
            ),
            "learning_field_count": len(
                source["learning_measurement"]["required_fields"]
            ),
        },
    }
    return contract, final_body


def main() -> None:
    contract, final_body = build_contract()
    CONTRACT_PATH.write_text(_canonical_json(contract), encoding="utf-8")
    FINAL_BODY_PATH.write_text(final_body, encoding="utf-8")
    print(
        "Built PCR-10 pre-Codex readiness: "
        f"{len(contract['activation_conditions'])} activation conditions, "
        f"{contract['quality_registry']['criterion_count']} quality criteria, "
        f"{contract['quality_registry']['developer_command_count']} developer commands, "
        "codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
