from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "configs/workstream6-permanent-release-record.yaml"
OUT = ROOT / "contracts/workstream6-permanent-release-record.json"
DOC = ROOT / "docs/68-WS6-16-PERMANENT-RELEASE-RECORD.md"
REPORT = ROOT / "reports/workstream6-permanent-release-preparation-evidence.md"


def load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def canon(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False) + "\n"


def build_records() -> tuple[dict[str, Any], str, str]:
    source = load(SRC)
    if source.get("work_package_id") != "WS6.16":
        raise ValueError("WS6.16 source has wrong work package")
    contract = {
        **source,
        "generated_from": SRC.relative_to(ROOT).as_posix(),
        "source_sha256": hashlib.sha256(SRC.read_bytes()).hexdigest(),
        "finalization_precondition_count": len(source["finalization_preconditions"]),
        "satisfied_finalization_precondition_count": sum(
            1 for item in source["finalization_preconditions"] if item["satisfied"] is True
        ),
        "required_release_binding_field_count": len(
            source["release_binding_contract"]["required_fields"]
        ),
    }
    doc = "\n".join([
        "# WS6.16 — Permanent release record",
        "",
        "> [!CAUTION]",
        "> **THE PERMANENT RELEASE DOES NOT EXIST YET.** This package prepares the only allowed post-merge finalization path. It must not fabricate an exact-main or hosted-evidence binding while WS6.8–WS6.15 remain unintegrated.",
        "",
        f"- Exact WS6.15 predecessor: `{source['predecessor']['head_sha']}` (PR #56).",
        f"- Observed integrated `main`: `{source['current_main']['observed_sha']}`, through `{source['current_main']['integrated_through']}`.",
        "- The permanent release path must remain absent in this preparation pull request.",
        "- The future release record binds the exact integrated parent-main SHA, the exact successful WS6.16 preparation merge reference, final-check run/job/artifact IDs, and the independently verified artifact digest.",
        "- Finalization downloads the retained artifact, verifies its archive SHA-256 and embedded all-tracked-file manifest, checks its run metadata, and requires the tested merge-ref tree to equal the integrated parent-main tree.",
        "- Predecessor evidence is historical only and cannot substitute for current final evidence.",
        "- The release record closes `WS6-BLOCK-006` and `WS6-CONSIST-010` only after those bindings are real and validated.",
        "- `WS6-CONSIST-006` remains a separate post-merge manual branch-cleanup gate.",
        "- Issue #19, clean macOS, Founder approval and a valid local single-use permit remain separate gates.",
        "- `codex_start_authorized=false`.",
        "",
        "## Required finalization sequence",
        "",
        "1. Integrate the predecessor stack through the WS6.16 preparation package with explicit Founder merge approval.",
        "2. Obtain a successful exact WS6.16 preparation merge-reference run and independently verify its retained artifact digest.",
        "3. Observe the exact integrated `main` SHA after the preparation package lands.",
        "4. Create `release/ws616-permanent-release-record` from that exact SHA.",
        "5. Run `scripts/finalize_workstream6_permanent_release.py` with the exact run/job/artifact/digest evidence.",
        "6. Review the generated permanent release, final evidence report and final defect ledger.",
        "7. Merge that small release-record change only with explicit Founder approval.",
        "",
        "## Current state",
        "",
        "- Release machinery prepared: `true`.",
        "- Permanent release record complete: `false`.",
        "- Final reconciliation complete: `false`.",
        "- All blocking defects closed: `false`.",
        "- WS6.16 complete: `false`.",
    ])
    report = "\n".join([
        "# WS6.16 permanent release preparation evidence",
        "",
        "<!-- Generated by scripts/build_workstream6_permanent_release_record.py. -->",
        "",
        f"- Predecessor head: `{source['predecessor']['head_sha']}`.",
        f"- Observed main: `{source['current_main']['observed_sha']}` through `{source['current_main']['integrated_through']}`.",
        f"- Finalization preconditions satisfied: `0/{len(source['finalization_preconditions'])}`.",
        f"- Required release binding fields: `{len(source['release_binding_contract']['required_fields'])}`.",
        "- Independent retained-artifact archive/manifest/run-metadata verification required: `true`.",
        "- Tested merge-ref and integrated parent-main tree identity required: `true`.",
        "- Permanent release path present: `false`.",
        "- `WS6-BLOCK-006`: pending truthful post-merge release.",
        "- `WS6-CONSIST-010`: pending current final evidence.",
        "- `WS6-CONSIST-006`: remains post-merge manual.",
        "- `codex_start_authorized=false`.",
    ])
    return contract, doc, report


def main() -> None:
    contract, doc, report = build_records()
    for path, text in (
        (OUT, canon(contract)),
        (DOC, doc + "\n"),
        (REPORT, report + "\n"),
    ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    print(
        "Built WS6.16 permanent release preparation: preconditions=0/6, "
        "required_bindings=9, permanent_release=false, ws616_complete=false, "
        "codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
