from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "repository-visibility-licence-posture.yaml"
OUTPUT_PATH = ROOT / "repository" / "repository-visibility-and-licence-posture.json"
REPORT_PATH = ROOT / "reports" / "pcfa03-repository-visibility-licence-posture-evidence.md"


def _canonical(value: object) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"


def _load_source() -> dict[str, Any]:
    value = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("PCFA-03 posture source must contain a mapping")
    return value


def build_records() -> tuple[dict[str, Any], str]:
    posture = dict(_load_source())
    if posture.get("work_package_id") != "PCFA-03":
        raise ValueError("PCFA-03 posture work-package identity drifted")
    if posture.get("posture_id") != "REPOSITORY-VISIBILITY-LICENCE-POSTURE":
        raise ValueError("PCFA-03 posture identity drifted")
    posture["generated_from"] = str(SOURCE_PATH.relative_to(ROOT))
    visibility = posture["visibility_posture"]
    licence = posture["licence_posture"]
    completion = posture["repository_side_completion"]
    report = "\n".join(
        [
            "# PCFA-03 repository visibility and licence posture evidence",
            "",
            "<!-- Generated by scripts/build_pcfa03_repository_posture.py. -->",
            "",
            f"- Posture: `{posture['posture_id']}`",
            f"- Required repository visibility for Codex launch: `{visibility['required_repository_visibility_for_codex_launch']}`",
            f"- Package-time observed visibility: `{visibility['package_time_observation']['visibility']}`",
            f"- Licence posture: `{licence['mode']}`",
            "- Selected open-source licence: `none`",
            "- Public distribution: `unauthorized`",
            "- External contributions: `unauthorized`",
            f"- Repository-side posture decision resolved: `{str(completion['policy_decision_resolved']).lower()}`",
            f"- Hosted private-visibility verification complete: `{str(completion['hosted_visibility_private_verified']).lower()}`",
            "- The live launch verifier must independently read GitHub repository visibility and reject public visibility.",
            "- WS6.13 licence placeholder remains historical package evidence and is not rewritten.",
            "- `codex_start_authorized=false`; merge, runtime, public distribution and external actions remain denied.",
            "",
        ]
    )
    return posture, report


def main() -> None:
    posture, report = build_records()
    OUTPUT_PATH.write_text(_canonical(posture), encoding="utf-8")
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(
        "Built PCFA-03 repository posture: required_visibility=private, "
        "licence=no_public_licence_grant_proprietary_internal, "
        "hosted_visibility_private_verified=false, codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
