from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "codex-phase0-issue.yaml"
HANDOFF_SOURCE_PATH = ROOT / "configs" / "codex-handoff.yaml"
OPERATING_CONTROLS_PATH = ROOT / "contracts" / "initial-operating-controls.json"
CONTRACT_PATH = ROOT / "contracts" / "codex-phase0-issue.json"
MARKDOWN_PATH = ROOT / "handoff" / "codex-phase0-issue.md"


def _load_yaml(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return value


def _load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def _canonical_json(value: object) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _humanize(value: str) -> str:
    return value.replace("_", " ").strip().capitalize()


def _render_task(task: dict[str, Any]) -> list[str]:
    lines = [f"### {task['id']} — {task['title']}", ""]
    dependencies = task.get("dependencies", [])
    lines.append("**Dependencies:** " + (", ".join(f"`{item}`" for item in dependencies) if dependencies else "None"))
    lines.extend(["", "**Deliverables:**"])
    lines.extend(f"- {_humanize(item)}" for item in task.get("deliverables", []))
    lines.extend(["", "**Acceptance:**"])
    lines.extend(f"- {_humanize(item)}" for item in task.get("acceptance", []))
    lines.append("")
    return lines


def render_issue_markdown(contract: dict[str, Any]) -> str:
    handoff = contract["handoff_snapshot"]
    target = contract["target_issue"]
    lines: list[str] = [
        "<!-- Generated by scripts/build_pcr09_codex_issue.py. Do not edit manually. -->",
        f"# {target['rewritten_title']}",
        "",
        "> [!CAUTION]",
        "> **NOT AUTHORISED TO START.** Opening, assigning, or rewriting this issue does not authorise Codex execution. Every activation item below must be independently verified, and the Founder must explicitly approve Phase 0 before any implementation begins.",
        "",
        "## Canonical authority",
        "",
        "- `AGENTS.md` is the controlling instruction.",
        "- `handoff/codex-phase0-handoff.json` is the machine-readable Phase 0 execution contract.",
        "- `contracts/codex-phase0-issue.json` and this generated issue body are a bounded execution summary; they do not override the controlling instruction or machine handoff.",
        "- Historical issue comments and chat snapshots are non-controlling. Exact counts and evidence must come from the current generated contracts and validation runs.",
        "",
        "## Activation gate — every item is required",
        "",
    ]
    for item in handoff["activation_conditions"]:
        lines.append(f"- [ ] `{item}`")
    lines.extend([
        "",
        "An agent must not infer completion of hosted settings, Founder approval, or the macOS environment from repository files. If any item is unverified, stop without changing implementation code.",
        "",
        "## Objective",
        "",
        "Validate the complete chat-first repository on the Founder’s clean macOS environment, then implement only Phase 0 — the controlled local foundation — around the existing governed assets. Integrate rather than replace the deterministic core, canonical contracts, runtime boundaries, Hermes restrictions, Northstar blueprint, operating controls, tests, fixtures, security records, and governance records.",
        "",
        "## Required read order",
        "",
    ])
    for index, path in enumerate(handoff["read_order"], start=1):
        lines.append(f"{index}. `{path}`")
    lines.extend([
        "",
        "## Preflight validation — before planning or code",
        "",
        "Run the following from the repository root. Stop on the first failure or generated diff.",
        "",
        "```bash",
    ])
    lines.extend(handoff["execution"]["required_commands"])
    lines.extend([
        "```",
        "",
        "Do not weaken tests, alter golden expectations merely to obtain a pass, or proceed when a prerequisite is stale, missing, or inconsistent.",
        "",
        "## Phase 0 task graph",
        "",
        "Implement in dependency order. Do not begin Phase 1.",
        "",
    ])
    for task in handoff["task_graph"]:
        lines.extend(_render_task(task))
    lines.extend([
        "## Required method",
        "",
    ])
    method_steps = [
        "Confirm every activation item with the Founder before implementation.",
        "Create and work only on `codex/phase-0-foundation`.",
        "Inspect the repository and macOS environment before changing files.",
        "Validate all pre-existing governed assets before adding application code.",
        "Produce a concise Phase 0 plan and decision register.",
        "Implement P0.1–P0.4 in dependency order using small, reviewable commits.",
        "Run the complete required command set and retain exact evidence.",
        "Perform a separate engineering, security, and quality review pass.",
        "Repair blocking defects without weakening controls or tests.",
        "Open a DRAFT pull request using `.github/pull_request_template.md`.",
        "Stop at the Phase 0 gate. Do not merge and do not progress to Phase 1.",
    ]
    lines.extend(f"{index}. {step}" for index, step in enumerate(method_steps, start=1))
    lines.extend(["", "## Prohibited actions", ""])
    lines.extend(f"- `{item}`" for item in handoff["prohibited_actions"])
    lines.extend(["", "## Stop conditions", ""])
    lines.extend(f"- `{item}`" for item in handoff["stop_conditions"])
    lines.extend([
        "",
        "Stop and escalate rather than improvising when any stop condition applies.",
        "",
        "## Acceptance evidence and Founder report",
        "",
        "The draft pull request and final Founder report must include:",
        "",
    ])
    lines.extend(f"- `{item}`" for item in handoff["completion_report_fields"])
    lines.extend([
        "- Clean macOS environment report and prerequisite versions.",
        "- Exact commands and full results, including deliberate CI failure-blocking evidence.",
        "- Local service health checks and restart-persistence evidence.",
        "- Confirmation that no secrets, real client data, paid resources, OAuth grants, DNS changes, external messages, or production deployments were used.",
        "- Independent review defect register and repairs.",
        "- Exact rollback and cleanup commands.",
        "",
        "## Phase 0 gate",
        "",
        "Completion means a draft pull request and a local demonstration packet are ready for Founder review. No substantive product workflow is required. Codex must not merge the pull request, activate any runtime, enable real client data, or begin Phase 1.",
        "",
        "## Supersession",
        "",
        "This is the single canonical Codex Phase 0 issue. Issue #2 is superseded as a duplicate after this body is applied. Its history remains available for audit, but it is not an additional workstream or authority source.",
        "",
        "## Rollback",
        "",
        "Before implementation starts, rollback is restoring the prior issue title/body and reopening issue #2 if needed. After implementation starts, follow the rollback instructions in the Phase 0 draft pull request and machine handoff.",
        "",
    ])
    return "\n".join(lines)


def build_codex_issue() -> tuple[dict[str, Any], str]:
    source = _load_yaml(SOURCE_PATH)
    handoff = _load_yaml(HANDOFF_SOURCE_PATH)
    operating = _load_json(OPERATING_CONTROLS_PATH)
    task_ids = [item.get("id") for item in handoff.get("task_graph", []) if isinstance(item, dict)]
    activation = handoff.get("activation_conditions", [])
    operating_activation = operating.get("activation_conditions", [])
    checks = {
        "phase0_target_preserved": handoff.get("target", {}).get("phase_number") == 0,
        "phase0_task_graph_exact": task_ids == ["P0.1", "P0.2", "P0.3", "P0.4"],
        "pcr09_activation_present": "pcr09_merged_to_main" in activation,
        "handoff_and_operating_activation_match": activation == operating_activation,
        "founder_approval_required": handoff.get("target", {}).get("start_requires_explicit_founder_approval") is True,
        "draft_pr_required": handoff.get("execution", {}).get("pull_request_mode") == "draft",
        "founder_merge_required": handoff.get("execution", {}).get("merge_requires_founder_approval") is True,
        "target_issue_is_one": source.get("target_issue", {}).get("number") == 1,
        "issue_two_superseded": source.get("supersession", {}).get("issue_numbers") == [2],
        "issue_is_non_authoritative_summary": source.get("authority", {}).get("issue_is_execution_summary_not_authority") is True,
        "all_rewrite_rules_enabled": all(value is True for value in source.get("rewrite_rules", {}).values()),
        "all_boundaries_denied": all(
            value is False
            for key, value in source.get("boundaries", {}).items()
            if key != "founder_accountability_preserved"
        ),
        "founder_accountability_preserved": source.get("boundaries", {}).get("founder_accountability_preserved") is True,
        "operating_controls_inactive": operating.get("boundaries", {}).get("initial_operating_controls_activation_authorized") is False,
    }
    contract = dict(source)
    contract["generated_from"] = "configs/codex-phase0-issue.yaml"
    contract["handoff_source"] = "configs/codex-handoff.yaml"
    contract["handoff_snapshot"] = {
        "target": handoff.get("target"),
        "read_order": handoff.get("read_order", []),
        "prerequisite_records": handoff.get("prerequisite_records", []),
        "task_graph": handoff.get("task_graph", []),
        "execution": handoff.get("execution", {}),
        "prohibited_actions": handoff.get("prohibited_actions", []),
        "stop_conditions": handoff.get("stop_conditions", []),
        "activation_conditions": activation,
        "completion_report_fields": handoff.get("completion_report_fields", []),
        "boundaries": handoff.get("boundaries", {}),
    }
    contract["readiness_snapshot"] = {
        "task_count": len(handoff.get("task_graph", [])),
        "read_order_count": len(handoff.get("read_order", [])),
        "prerequisite_record_count": len(handoff.get("prerequisite_records", [])),
        "required_command_count": len(handoff.get("execution", {}).get("required_commands", [])),
        "prohibited_action_count": len(handoff.get("prohibited_actions", [])),
        "stop_condition_count": len(handoff.get("stop_conditions", [])),
        "activation_condition_count": len(activation),
        "completion_report_field_count": len(handoff.get("completion_report_fields", [])),
        "superseded_issue_count": len(source.get("supersession", {}).get("issue_numbers", [])),
        "checks": checks,
        "local_prerequisites_passed": all(checks.values()),
        "github_issue_sync_verified": False,
        "codex_start_authorized": False,
        "phase1_authorized": False,
    }
    markdown = render_issue_markdown(contract)
    contract["generated_issue"] = {
        "title": source["target_issue"]["rewritten_title"],
        "body_path": source["target_issue"]["canonical_body_path"],
        "body_sha256": _sha256(markdown),
        "body_character_count": len(markdown),
        "body_line_count": markdown.count("\n") + 1,
        "github_issue_sync_verified": False,
    }
    return contract, markdown


def main() -> None:
    contract, markdown = build_codex_issue()
    CONTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    MARKDOWN_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONTRACT_PATH.write_text(_canonical_json(contract), encoding="utf-8")
    MARKDOWN_PATH.write_text(markdown, encoding="utf-8")
    readiness = contract["readiness_snapshot"]
    print(
        "Built PCR-09 first Codex issue rewrite: "
        f"issue #{contract['target_issue']['number']}, "
        f"{readiness['task_count']} Phase 0 tasks, "
        f"{readiness['read_order_count']} read-order files, "
        f"{readiness['activation_condition_count']} activation conditions, "
        "codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
