from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "configs" / "codex-phase0-launch-control.yaml"
PRIOR_READINESS_PATH = ROOT / "contracts" / "pre-codex-readiness.json"
WORKSTREAM4_PATH = ROOT / "contracts" / "workstream4-readiness.json"
PCR10_BODY_PATH = ROOT / "handoff" / "codex-phase0-issue-pcr10.md"
CONTRACT_PATH = ROOT / "contracts" / "codex-phase0-launch-control.json"
ISSUE_BODY_PATH = ROOT / "handoff" / "codex-phase0-issue-workstream5.md"
RELEASE_PATH = ROOT / "releases" / "codex-phase0-launch-control-2026-08-06.json"

TEMPLATE_PATHS = {
    "hosted_controls": ROOT / "handoff" / "codex-phase0-hosted-controls-attestation.template.json",
    "clean_macos": ROOT / "handoff" / "codex-phase0-clean-macos-attestation.template.json",
    "founder_approval": ROOT / "handoff" / "codex-phase0-founder-authorization.template.json",
    "launch_ack": ROOT / "handoff" / "codex-phase0-launch-ack.template.json",
}


def _load_yaml(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return value


def _load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def _canonical_json(value: object) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"


def _sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _insert_after(lines: list[str], anchor: str, new_lines: list[str]) -> None:
    if anchor not in lines:
        raise ValueError(f"Issue-body anchor missing: {anchor}")
    index = lines.index(anchor)
    lines[index + 1:index + 1] = new_lines


def _insert_before(lines: list[str], anchor: str, new_lines: list[str]) -> None:
    if anchor not in lines:
        raise ValueError(f"Issue-body anchor missing: {anchor}")
    index = lines.index(anchor)
    lines[index:index] = new_lines


def _replace_line(lines: list[str], old: str, new: str) -> None:
    if old not in lines:
        raise ValueError(f"Issue-body line missing: {old}")
    lines[lines.index(old)] = new


def build_issue_body(source: dict[str, Any]) -> str:
    lines = PCR10_BODY_PATH.read_text(encoding="utf-8").splitlines()
    if not lines or "build_pcr10_pre_codex_readiness.py" not in lines[0]:
        raise ValueError("PCR-10 generated issue body header is missing")
    lines[0] = "<!-- Generated by scripts/build_workstream5_launch_control.py. Do not edit manually. -->"

    _insert_after(
        lines,
        "- `contracts/pre-codex-readiness.json` is the final pre-start release and quality gate and extends, but does not replace, the Phase 0 execution task graph.",
        [
            "- `contracts/workstream4-readiness.json` records hosted-control, durable-evidence and clean-environment prerequisites without claiming their manual completion.",
            "- `contracts/codex-phase0-launch-control.json` is the final launch-control contract. It does not grant permission by itself.",
            "- `handoff/codex-phase0-issue-workstream5.md` is the final generated canonical issue body after Workstream 5.",
        ],
    )

    read_order_anchor = "29. `handoff/codex-phase0-issue-pcr10.md`"
    _insert_after(
        lines,
        read_order_anchor,
        [
            "30. `docs/50-WORKSTREAM-4-HOSTED-CONTROLS-EVIDENCE-AND-ENVIRONMENT-READINESS.md`",
            "31. `contracts/workstream4-readiness.json`",
            "32. `docs/51-WORKSTREAM-5-CODEX-PHASE-0-LAUNCH-CONTROL.md`",
            "33. `contracts/codex-phase0-launch-control.json`",
            "34. `handoff/codex-phase0-issue-workstream5.md`",
            "35. `handoff/codex-phase0-hosted-controls-attestation.template.json`",
            "36. `handoff/codex-phase0-clean-macos-attestation.template.json`",
            "37. `handoff/codex-phase0-founder-authorization.template.json`",
            "38. `handoff/codex-phase0-launch-ack.template.json`",
        ],
    )

    _insert_after(
        lines,
        "python scripts/build_pcr10_pre_codex_readiness.py",
        [
            "python scripts/build_workstream4_readiness.py",
            "python scripts/build_workstream5_launch_control.py",
        ],
    )
    _insert_after(
        lines,
        "python scripts/validate_pcr10_pre_codex_readiness.py",
        [
            "python scripts/validate_workstream4_readiness.py",
            "python scripts/validate_workstream5_launch_control.py",
            "python scripts/prepare_codex_phase0_launch.py --self-test",
            "git diff --exit-code",
        ],
    )

    launch_section = [
        "## Workstream 5 launch control",
        "",
        "A green workflow, an assigned issue, a branch name, or this issue body is not launch authorization. Codex implementation may begin only after `scripts/prepare_codex_phase0_launch.py` creates a valid local permit from three independent evidence bundles bound to the same current `main` SHA:",
        "",
        "1. completed GitHub-hosted controls and historical branch cleanup recorded through issue #19;",
        "2. a redacted clean-macOS doctor report plus Founder environment attestation; and",
        "3. an explicit Founder decision approving **Codex Phase 0 only** against the exact current `main` SHA.",
        "",
        "The permit is stored only under the ignored `.local/codex-phase0-launch/` directory, is single-use, becomes stale after any `main` or evidence change, and never authorizes merge or Phase 1. The first Codex commit must add `governance/codex-phase0-launch-ack.json` containing the permit ID and approved base SHA.",
        "",
        "### Launch preparation command",
        "",
        "```bash",
        "python scripts/prepare_codex_phase0_launch.py \\",
        "  --hosted-controls .local/codex-phase0-launch/hosted-controls.json \\",
        "  --macos-report .local/codex-phase0-launch/macos-doctor.json \\",
        "  --macos-attestation .local/codex-phase0-launch/macos-attestation.json \\",
        "  --founder-approval .local/codex-phase0-launch/founder-approval.json",
        "```",
        "",
        "The command is non-mutating with respect to GitHub: it does not create a branch, open a pull request, merge code, activate a runtime, or enable any service. A failure must stop launch preparation.",
        "",
        "### Permit scope",
        "",
        "- Approved tasks are exactly P0.1–P0.4 on `codex/phase-0-foundation`.",
        "- The pull request must remain draft and unmerged pending Founder review.",
        "- Synthetic data only; no paid service, credential, OAuth, DNS, external communication, staging or production action is authorized.",
        "- Any SHA drift, issue-state drift, evidence-digest drift, existing Codex branch/PR, scope widening or revoked approval invalidates the permit.",
        "",
    ]
    _insert_before(lines, "## Required method", launch_section)

    _replace_line(
        lines,
        "2. Create and work only on `codex/phase-0-foundation`.",
        "2. After a valid Workstream 5 permit is issued, create and work only on `codex/phase-0-foundation` from the approved exact `main` SHA.",
    )
    _insert_after(
        lines,
        "- PCR-10 readiness-contract validation and the exact final issue-body digest.",
        [
            "- Workstream 5 launch-permit ID, approved exact `main` SHA and all evidence digests.",
            "- First-commit launch acknowledgement and proof that the branch began from the approved SHA.",
        ],
    )

    supersession_index = lines.index("## Supersession")
    for index in range(supersession_index + 1, min(supersession_index + 8, len(lines))):
        if lines[index].startswith("This remains the single canonical Codex Phase 0 issue"):
            lines[index] = (
                "This remains the single canonical Codex Phase 0 issue. Workstream 5 owns the final launch-control "
                "protocol and generated issue body; PCR-10 remains the release and quality predecessor. Issue #2 "
                "remains superseded as a duplicate and is not an additional workstream or authority source."
            )
            break
    else:
        raise ValueError("Supersession paragraph is missing")

    rollback_index = lines.index("## Rollback")
    for index in range(rollback_index + 1, min(rollback_index + 8, len(lines))):
        if lines[index].startswith("Before implementation starts"):
            lines[index] = (
                "Before implementation starts, rollback is deleting the untracked local permit and evidence bundle, "
                "restoring the prior canonical issue body if needed, and leaving the Codex branch absent. After "
                "implementation starts, follow the rollback instructions in the Phase 0 draft pull request and "
                "machine handoff."
            )
            break
    else:
        raise ValueError("Rollback paragraph is missing")

    return "\n".join(lines).rstrip() + "\n"


def build_templates(source: dict[str, Any]) -> dict[str, dict[str, Any]]:
    zero_sha = "0" * 40
    zero_digest = "0" * 64
    hosted_controls = {
        "schema_version": "1.0.0",
        "evidence_type": "github_hosted_controls_attestation",
        "repository": source["repository"],
        "issue_number": 19,
        "issue_state": "open",
        "issue_state_reason": None,
        "approved_main_sha": zero_sha,
        "recorded_at": None,
        "attested_by": "rayrayxing",
        "controls": {
            "github_mfa_enabled": False,
            "pull_request_required_for_main": False,
            "final_launch_status_check_required_for_main": False,
            "stale_approvals_dismissed": False,
            "review_conversation_resolution_required": False,
            "force_push_to_main_blocked": False,
            "main_branch_deletion_blocked": False,
            "merged_head_branches_auto_deleted": False,
        },
        "branch_cleanup": {
            "complete": False,
            "remaining_branches": [],
            "inventory_sha256": zero_digest,
        },
        "evidence_attachments": [],
        "attested": False,
    }
    clean_macos = {
        "schema_version": "1.0.0",
        "evidence_type": "clean_macos_environment_attestation",
        "repository": source["repository"],
        "approved_main_sha": zero_sha,
        "doctor_report_sha256": zero_digest,
        "recorded_at": None,
        "attested_by": "rayrayxing",
        "manual_attestations": {
            "clean_machine_available": False,
            "no_real_client_files_present": False,
            "no_repository_credentials_present": False,
            "no_paid_service_or_trial_required": False,
            "founder_environment_attestation_received": False,
        },
        "clean_macos_environment_verified": False,
        "attested": False,
    }
    founder_approval = {
        "schema_version": "1.0.0",
        "evidence_type": "founder_codex_phase0_authorization",
        "repository": source["repository"],
        "canonical_issue": 1,
        "decision": "not_approved",
        "approved_main_sha": zero_sha,
        "approved_phase": "Codex Phase 0 only",
        "approved_tasks": source["launch_target"]["permitted_tasks"],
        "required_branch": source["launch_target"]["required_branch"],
        "draft_pull_request_required": True,
        "merge_authorized": False,
        "phase1_authorized": False,
        "authorized_at": None,
        "attested_by": "rayrayxing",
        "attested": False,
    }
    launch_ack = {
        "schema_version": "1.0.0",
        "ack_type": "codex_phase0_launch_acknowledgement",
        "launch_id": zero_digest,
        "approved_main_sha": zero_sha,
        "branch": source["launch_target"]["required_branch"],
        "permit_sha256": zero_digest,
        "phase": "Codex Phase 0 only",
        "tasks": source["launch_target"]["permitted_tasks"],
        "draft_pull_request_required": True,
        "merge_authorized": False,
        "phase1_authorized": False,
    }
    return {
        "hosted_controls": hosted_controls,
        "clean_macos": clean_macos,
        "founder_approval": founder_approval,
        "launch_ack": launch_ack,
    }


def build_records() -> tuple[dict[str, Any], str, dict[str, dict[str, Any]], dict[str, Any]]:
    source = _load_yaml(SOURCE_PATH)
    prior = _load_json(PRIOR_READINESS_PATH)
    workstream4 = _load_json(WORKSTREAM4_PATH)
    issue_body = build_issue_body(source)
    templates = build_templates(source)

    prior_checks = {
        "pre_codex_release_integrated": (
            prior.get("status") == "chat_first_complete_integrated"
            and prior.get("readiness_snapshot", {}).get("release_integration_complete") is True
        ),
        "pre_codex_release_unauthorized": (
            prior.get("readiness_snapshot", {}).get("codex_start_authorized") is False
        ),
        "workstream4_repository_preparation_complete": (
            workstream4.get("readiness_snapshot", {}).get("repository_side_prerequisites_passed") is True
        ),
        "workstream4_manual_gates_remain_pending": (
            workstream4.get("readiness_snapshot", {}).get("hosted_controls_verified") is False
            and workstream4.get("readiness_snapshot", {}).get("clean_macos_environment_verified") is False
            and workstream4.get("readiness_snapshot", {}).get("codex_start_authorized") is False
        ),
        "prior_evidence_digests_declared": len(source["prior_evidence"]) == 5,
        "approved_main_sha_unbound": source["sha_binding"]["approved_main_sha"] is None,
        "all_external_gates_pending": (
            source["readiness"]["hosted_controls_verified"] is False
            and source["readiness"]["clean_macos_environment_verified"] is False
            and source["readiness"]["explicit_founder_phase0_approval_received"] is False
        ),
        "codex_start_unauthorized": source["readiness"]["codex_start_authorized"] is False,
        "all_authority_boundaries_denied": all(
            value is False
            for key, value in source["boundaries"].items()
            if key != "founder_accountability_preserved"
        ),
        "founder_accountability_preserved": source["boundaries"]["founder_accountability_preserved"] is True,
    }

    rendered_templates = {
        key: _canonical_json(value) for key, value in templates.items()
    }
    template_registry = {
        key: {
            "path": str(TEMPLATE_PATHS[key].relative_to(ROOT)),
            "sha256": _sha256_text(rendered),
        }
        for key, rendered in rendered_templates.items()
    }

    release = {
        "schema_version": "1.0.0",
        "release_id": "CODEX-PHASE0-LAUNCH-CONTROL-2026-08-06",
        "release_class": "permanent_repository_launch_control",
        "repository": source["repository"],
        "canonical_branch": source["canonical_branch"],
        "pre_workstream_main_sha": source["pre_workstream_main_sha"],
        "prior_evidence": source["prior_evidence"],
        "generated_issue_body": {
            "path": str(ISSUE_BODY_PATH.relative_to(ROOT)),
            "sha256": _sha256_text(issue_body),
            "line_count": len(issue_body.splitlines()),
        },
        "template_registry": template_registry,
        "launch_target": source["launch_target"],
        "sha_binding": source["sha_binding"],
        "authorization": {
            "hosted_controls_verified": False,
            "clean_macos_environment_verified": False,
            "explicit_founder_phase0_approval_received": False,
            "approved_main_sha_bound": False,
            "launch_permit_issued": False,
            "codex_start_authorized": False,
        },
        "rollback": {
            "before_launch": "delete only .local/codex-phase0-launch and keep the Codex branch absent",
            "after_launch": "follow the draft Phase 0 pull request rollback and stop at the Founder gate",
        },
    }
    release_text = _canonical_json(release)

    contract = {
        **source,
        "generated_from": str(SOURCE_PATH.relative_to(ROOT)),
        "generated_issue": {
            "body_path": str(ISSUE_BODY_PATH.relative_to(ROOT)),
            "body_sha256": _sha256_text(issue_body),
            "body_line_count": len(issue_body.splitlines()),
            "body_character_count": len(issue_body),
            "github_issue_sync_verified": False,
        },
        "template_registry": template_registry,
        "launch_protocol_registry": {
            "permitted_task_count": len(source["launch_target"]["permitted_tasks"]),
            "allowed_scope_count": len(source["allowed_scope"]),
            "prohibited_scope_count": len(source["prohibited_scope"]),
            "stop_condition_count": len(source["stop_conditions"]),
            "preflight_command_count": len(source["required_preflight_commands"]),
            "revocation_condition_count": len(source["launch_permit"]["revocation_conditions"]),
        },
        "readiness_snapshot": {
            "checks": prior_checks,
            "repository_launch_control_complete": all(prior_checks.values()),
            "generated_issue_ready_for_sync": True,
            "github_issue_sync_verified": False,
            "hosted_controls_verified": False,
            "clean_macos_environment_verified": False,
            "explicit_founder_phase0_approval_received": False,
            "approved_main_sha_bound": False,
            "launch_permit_issued": False,
            "codex_start_authorized": False,
            "next_permitted_phase_after_all_gates": "Codex Phase 0 only",
        },
        "durable_release": {
            "path": str(RELEASE_PATH.relative_to(ROOT)),
            "release_id": release["release_id"],
            "sha256": _sha256_text(release_text),
        },
    }
    return contract, issue_body, templates, release


def main() -> None:
    contract, issue_body, templates, release = build_records()
    CONTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    ISSUE_BODY_PATH.parent.mkdir(parents=True, exist_ok=True)
    RELEASE_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONTRACT_PATH.write_text(_canonical_json(contract), encoding="utf-8")
    ISSUE_BODY_PATH.write_text(issue_body, encoding="utf-8")
    for key, value in templates.items():
        TEMPLATE_PATHS[key].write_text(_canonical_json(value), encoding="utf-8")
    RELEASE_PATH.write_text(_canonical_json(release), encoding="utf-8")
    snapshot = contract["readiness_snapshot"]
    print(
        "Built Workstream 5 Codex Phase 0 launch control: "
        f"{contract['launch_protocol_registry']['preflight_command_count']} preflight commands, "
        f"{contract['launch_protocol_registry']['stop_condition_count']} stop conditions, "
        f"repository_launch_control_complete={str(snapshot['repository_launch_control_complete']).lower()}, "
        "hosted_controls_verified=false, clean_macos_environment_verified=false, "
        "founder_approval=false, codex_start_authorized=false."
    )


if __name__ == "__main__":
    main()
