from __future__ import annotations

import copy
import hashlib
import json
import re
from typing import Any

import yaml

from codex_phase0_launch_core import ROOT, digest_file, load_json

SOURCE = ROOT / "configs" / "pcfa08-final-pre-codex-cross-authority-acceptance.yaml"
RECORD = ROOT / "repository" / "pcfa08-final-pre-codex-cross-authority-acceptance.json"
REPORT = ROOT / "reports" / "pcfa08-final-pre-codex-cross-authority-acceptance-evidence.md"
BACKLOG = ROOT / "docs" / "11-BUILD-BACKLOG.md"
_SHA_RE = re.compile(r"^[0-9a-f]{40}$")
_DIGEST_RE = re.compile(r"^[0-9a-f]{64}$")

_MANUAL_IDS = [
    "repository_visibility_private_verified",
    "github_hosted_controls_verified",
    "historical_branch_cleanup_complete",
    "clean_macos_environment_verified",
    "live_issue_bodies_synchronized",
    "explicit_founder_phase0_approval_received",
    "approved_main_sha_bound",
    "launch_permit_issued",
]
_TARGET = {
    "permitted_phase": "Codex Phase 0 only",
    "permitted_tasks": ["P0.1", "P0.2", "P0.3", "P0.4"],
    "required_branch": "codex/phase-0-foundation",
    "required_pull_request_state": "draft",
    "required_status_check": "Validate final pre-Codex canonical handoff and complete release",
    "implementation_may_start_only_after_valid_permit": True,
}
_SUMMARY = {
    "authority_input_count": 9,
    "cross_authority_invariant_count": 18,
    "manual_launch_gate_count": 8,
    "planned_branch_deletion_count": 65,
    "retained_branch_count_at_cleanup_completion": 1,
    "pcfa07_obligation_count": 93,
    "pcfa07_planned_test_count": 93,
    "new_imp_phase_count": 0,
    "new_imp_task_count": 0,
    "phase0_new_obligation_count": 0,
}


def _inventory_digest(names: list[str]) -> str:
    payload = json.dumps(sorted(names), ensure_ascii=False, separators=(",", ":")) + "\n"
    return hashlib.sha256(payload.encode()).hexdigest()


def _source() -> dict[str, Any]:
    value = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("PCFA-08 source must be a mapping")
    return value


def build_records() -> tuple[dict[str, Any], str]:
    source = _source()
    record = copy.deepcopy(source)
    bound = []
    for item in source["authority_inputs"]:
        path = ROOT / item["path"]
        if not path.is_file():
            raise ValueError(f"PCFA-08 authority input missing: {item['path']}")
        bound.append({**item, "sha256": digest_file(path)})
    record["authority_inputs"] = bound
    record["cross_authority_invariants"] = [{**item, "accepted": True} for item in source["cross_authority_invariants"]]
    record["generated_from"] = str(SOURCE.relative_to(ROOT))
    plan = record["branch_cleanup_plan"]
    record["summary"] = {
        **_SUMMARY,
        "authority_input_count": len(bound),
        "cross_authority_invariant_count": len(record["cross_authority_invariants"]),
        "manual_launch_gate_count": len(record["manual_launch_gates"]),
        "planned_branch_deletion_count": len(plan["delete_after_dependency_order_integration"]),
        "retained_branch_count_at_cleanup_completion": len(plan["retain_branches"]),
    }
    report = "\n".join([
        "# PCFA-08 final pre-Codex cross-authority acceptance evidence", "",
        "<!-- Generated by scripts/build_pcfa08_final_acceptance.py. -->", "",
        "- Work package: `PCFA-08`",
        f"- Authority inputs SHA-256-bound: `{len(bound)}`",
        f"- Cross-authority invariants accepted: `{len(record['cross_authority_invariants'])}`",
        f"- Manual launch gates intentionally pending: `{len(record['manual_launch_gates'])}`",
        f"- Exact post-integration branch deletion plan: `{len(plan['delete_after_dependency_order_integration'])}` branches",
        "- Required final live branch inventory before Codex branch creation: `[\"main\"]`",
        "- Every deleted branch requires its final 40-hex SHA as retained evidence.",
        "- PCFA-07 remains exactly 93 obligations / 93 planned tests with zero IMP-P0 widening.",
        "- Repository-side final cross-authority acceptance: `true`.",
        "- Manual launch evidence complete: `false`.",
        "- `codex_start_authorized=false`; no implementation or branch creation is authorized by this package.", "",
    ])
    return record, report


def _need(errors: list[str], ok: bool, msg: str) -> None:
    if not ok:
        errors.append(msg)


def backlog_semantic_failures(text: str | None = None) -> list[str]:
    value = BACKLOG.read_text(encoding="utf-8") if text is None else text
    checks = [
        ("Resolved PCFA-03 repository/licence posture: private/internal development, no public licence grant" in value,
         "IMP-P0 backlog does not consume the resolved PCFA-03 private/internal no-public-licence posture"),
        ("Licence decision placeholder" not in value,
         "IMP-P0 backlog regressed to the historical licence-decision placeholder"),
        ("100% of Founder-approved canonical methodology sources are accounted for" in value,
         "IMP-P1 backlog does not require complete Founder-approved source accounting"),
        ("Method-count coverage is reported as a secondary diagnostic only" in value
         and "Initial 150-plus method records are structured and searchable" not in value,
         "IMP-P1 backlog regressed to a count-only methodology completeness gate"),
    ]
    return [msg for ok, msg in checks if not ok]


def record_failures(record: dict[str, Any]) -> list[str]:
    e = backlog_semantic_failures()
    a = record.get("repository_acceptance", {})
    c = record.get("branch_cleanup_plan", {})
    t = record.get("launch_target", {})
    b = record.get("boundaries", {})
    inv = record.get("cross_authority_invariants", [])
    manual = record.get("manual_launch_gates", [])
    auth = record.get("authority_inputs", [])
    delete = c.get("delete_after_dependency_order_integration", [])
    _need(e, record.get("work_package_id") == "PCFA-08", "PCFA-08 identity drifted")
    _need(e, record.get("status") == "repository_cross_authority_accepted_manual_launch_gates_pending", "PCFA-08 status drifted")
    _need(e, len(auth) == 9, "PCFA-08 authority input count drifted")
    _need(e, all(isinstance(x.get("sha256"), str) and len(x["sha256"]) == 64 for x in auth), "PCFA-08 authority digest binding is incomplete")
    _need(e, len(inv) == 18 and all(x.get("accepted") is True for x in inv), "PCFA-08 cross-authority invariants are incomplete")
    _need(e, a.get("prior_pcfa_packages_required") == [f"PCFA-0{i}" for i in range(1, 8)], "PCFA-08 predecessor package coverage drifted")
    _need(e, all(a.get(k) is v for k, v in {
        "all_prior_repository_side_requirements_consistent": True,
        "implementation_backlog_reconciled": True,
        "phase0_scope_unchanged": True,
        "repository_side_cross_authority_acceptance_complete": True,
        "manual_launch_evidence_complete": False,
        "launch_authorization_complete": False,
    }.items()), "PCFA-08 repository acceptance semantics drifted")
    _need(e, [x.get("id") for x in manual] == _MANUAL_IDS, "PCFA-08 manual launch gate registry drifted")
    _need(e, all(x.get("required_value") is True and str(x.get("status", "")).startswith("pending_") for x in manual), "PCFA-08 manual launch gates must remain pending")
    _need(e, c.get("policy") == "exact_allowlist_only", "PCFA-08 cleanup policy drifted")
    _need(e, (c.get("observed_repository_branch_count_before_pcfa08_branch"), c.get("observed_non_main_branch_count_before_pcfa08_branch"), c.get("pcfa08_branch_added_after_observation"), c.get("expected_cleanup_branch_count_after_pcfa08_integration")) == (65, 64, True, 65), "PCFA-08 branch observation/count semantics drifted")
    _need(e, len(delete) == len(set(delete)) == 65 and "main" not in delete and all(isinstance(x, str) and x and not any(y in x for y in "*?[]") for x in delete), "PCFA-08 exact branch cleanup allowlist drifted")
    _need(e, c.get("retain_branches") == c.get("final_live_branch_inventory_must_equal") == ["main"]
          and all(c.get(k) is True for k in ["require_final_sha_for_every_deleted_branch", "require_merged_ancestry_or_explicit_obsolete_classification", "wildcards_prohibited", "codex_phase0_branch_must_be_absent_before_cleanup_completion", "unexpected_branch_requires_explicit_reconciliation"]), "PCFA-08 branch cleanup evidence semantics drifted")
    _need(e, t == _TARGET, "PCFA-08 launch target drifted")
    _need(e, b.get("founder_accountability_preserved") is True and all(v is False for k, v in b.items() if k != "founder_accountability_preserved"), "PCFA-08 authorization boundary drifted")
    _need(e, record.get("summary") == _SUMMARY, "PCFA-08 summary drifted")
    return e


def state_failures(state: dict[str, Any], record: dict[str, Any] | None = None) -> list[str]:
    value = record or load_json(RECORD)
    e = record_failures(value)
    auth = state.get("current_authority", {})
    ready = state.get("repository_readiness", {})
    manual = state.get("manual_launch_gates", {})
    _need(e, auth.get("final_pre_codex_cross_authority_acceptance") == "repository/pcfa08-final-pre-codex-cross-authority-acceptance.json"
          and auth.get("final_pre_codex_cross_authority_acceptance_sha256") == (digest_file(RECORD) if RECORD.is_file() else None), "current state does not bind PCFA-08 final acceptance")
    _need(e, ready.get("pcfa08_final_cross_authority_acceptance_complete") is True, "current readiness omits PCFA-08 completion")
    _need(e, state.get("launch_target", {}).get("permitted_tasks") == _TARGET["permitted_tasks"], "PCFA-08 state widened Phase 0")
    _need(e, manual.get("codex_start_authorized") is False and manual.get("launch_permit_issued") is False, "PCFA-08 state prematurely authorized launch")
    _need(e, state.get("launch_permit", {}).get("stale_on_pcfa08_final_acceptance_change") is True, "launch permit does not explicitly stale on PCFA-08 acceptance drift")
    return e


def hosted_cleanup_failures(record: dict[str, Any], hosted: dict[str, Any], live_branch_names: list[str]) -> list[str]:
    e = record_failures(record)
    cleanup = hosted.get("branch_cleanup", {})
    deleted = cleanup.get("deleted_branches", [])
    expected = set(record["branch_cleanup_plan"]["delete_after_dependency_order_integration"])
    names = [x.get("branch") for x in deleted if isinstance(x, dict)]
    _need(e, cleanup.get("complete") is True, "PCFA-08 exact branch cleanup is incomplete")
    _need(e, cleanup.get("remaining_branches") == ["main"], "PCFA-08 attested final branch inventory must contain only main")
    _need(e, sorted(live_branch_names) == ["main"], "live GitHub branch inventory must contain only main before Codex launch")
    _need(e, _DIGEST_RE.fullmatch(str(cleanup.get("inventory_sha256", ""))) is not None and cleanup.get("inventory_sha256") == _inventory_digest(live_branch_names), "branch inventory SHA-256 does not bind the independently observed live branch list")
    _need(e, len(deleted) == len(expected) and len(names) == len(set(names)) and set(names) == expected, "deleted-branch evidence does not exactly cover the PCFA-08 allowlist")
    _need(e, all(isinstance(x, dict) and _SHA_RE.fullmatch(str(x.get("final_sha", ""))) is not None and x.get("disposition") in {"merged", "obsolete", "superseded"} for x in deleted), "every deleted branch requires final SHA and governed disposition evidence")
    return e


def _mutate(value: dict[str, Any], path: tuple[str, ...], replacement: Any) -> dict[str, Any]:
    out = copy.deepcopy(value)
    node: Any = out
    for part in path[:-1]:
        node = node[int(part)] if part.isdigit() else node[part]
    last = path[-1]
    if last.isdigit():
        node[int(last)] = replacement
    else:
        node[last] = replacement
    return out


def run_self_test(state: dict[str, Any]) -> int:
    record = load_json(RECORD)
    if (errors := state_failures(state, record)):
        raise SystemExit("PCFA-08 final acceptance rejected: " + "; ".join(errors))
    rejected = 0
    state_cases = [
        ("authority", ("current_authority", "final_pre_codex_cross_authority_acceptance"), "wrong.json"),
        ("digest", ("current_authority", "final_pre_codex_cross_authority_acceptance_sha256"), "0" * 64),
        ("readiness", ("repository_readiness", "pcfa08_final_cross_authority_acceptance_complete"), False),
        ("p0", ("launch_target", "permitted_tasks"), ["P0.1", "P1.1"]),
    ]
    for label, path, replacement in state_cases:
        if not state_failures(_mutate(state, path, replacement), record):
            raise SystemExit(f"PCFA-08 state mutation not rejected: {label}")
        rejected += 1
    record_cases = [
        ("invariant", ("cross_authority_invariants", "0", "accepted"), False),
        ("manual", ("repository_acceptance", "manual_launch_evidence_complete"), True),
        ("authorization", ("boundaries", "codex_start_authorized"), True),
        ("cleanup count", ("branch_cleanup_plan", "expected_cleanup_branch_count_after_pcfa08_integration"), 64),
        ("retain main", ("branch_cleanup_plan", "retain_branches"), ["main", "other"]),
        ("wildcard", ("branch_cleanup_plan", "delete_after_dependency_order_integration", "0"), "governance/*"),
        ("p0 target", ("launch_target", "permitted_tasks"), ["P0.1", "P1.1"]),
    ]
    for label, path, replacement in record_cases:
        if not record_failures(_mutate(record, path, replacement)):
            raise SystemExit(f"PCFA-08 record mutation not rejected: {label}")
        rejected += 1
    hosted = {"branch_cleanup": {"complete": True, "remaining_branches": ["main"], "inventory_sha256": _inventory_digest(["main"]), "deleted_branches": [{"branch": name, "final_sha": "a" * 40, "disposition": "obsolete"} for name in record["branch_cleanup_plan"]["delete_after_dependency_order_integration"]]}}
    if hosted_cleanup_failures(record, hosted, ["main"]):
        raise SystemExit("PCFA-08 valid synthetic cleanup evidence was rejected")
    bad = copy.deepcopy(hosted)
    bad["branch_cleanup"]["deleted_branches"][0]["final_sha"] = "bad"
    for label, value, live in [("malformed cleanup SHA", bad, ["main"]), ("live branch inventory drift", hosted, ["main", "other"])]:
        if not hosted_cleanup_failures(record, value, live):
            raise SystemExit(f"PCFA-08 {label} was not rejected")
        rejected += 1
    text = BACKLOG.read_text(encoding="utf-8")
    cases = [
        ("licence placeholder", text.replace("Resolved PCFA-03 repository/licence posture: private/internal development, no public licence grant, and no repository `LICENSE` unless a later explicit Founder licence ADR changes that posture", "Licence decision placeholder")),
        ("licence posture removed", text.replace("- Resolved PCFA-03 repository/licence posture: private/internal development, no public licence grant, and no repository `LICENSE` unless a later explicit Founder licence ADR changes that posture\n", "")),
        ("count-only library gate", text.replace("- 100% of Founder-approved canonical methodology sources are accounted for as ingested/structured, duplicate, superseded, quarantined, or explicitly excluded with a recorded reason", "- Initial 150-plus method records are structured and searchable")),
        ("method count made controlling", text.replace("- Method-count coverage is reported as a secondary diagnostic only; it is not a substitute for complete approved-source accounting\n", "")),
    ]
    for label, value in cases:
        if not backlog_semantic_failures(value):
            raise SystemExit(f"PCFA-08 backlog semantic mutation not rejected: {label}")
        rejected += 1
    return rejected


final_acceptance_failures = state_failures
