from __future__ import annotations

import copy
import hashlib
import json
import re
from pathlib import Path
from typing import Any

import yaml

from codex_phase0_launch_core import ROOT, digest_file, load_json

SOURCE = ROOT / "configs" / "pcfa08-final-pre-codex-cross-authority-acceptance.yaml"
RECORD = ROOT / "repository" / "pcfa08-final-pre-codex-cross-authority-acceptance.json"
REPORT = ROOT / "reports" / "pcfa08-final-pre-codex-cross-authority-acceptance-evidence.md"
_SHA_RE = re.compile(r"^[0-9a-f]{40}$")
_DIGEST_RE = re.compile(r"^[0-9a-f]{64}$")


def _inventory_digest(branch_names: list[str]) -> str:
    payload = json.dumps(sorted(branch_names), ensure_ascii=False, separators=(",", ":")) + "\n"
    return hashlib.sha256(payload.encode()).hexdigest()


def _source() -> dict[str, Any]:
    value = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("PCFA-08 source must be a mapping")
    return value


def build_records() -> tuple[dict[str, Any], str]:
    source = _source()
    record = copy.deepcopy(source)
    authority_inputs: list[dict[str, Any]] = []
    for item in source["authority_inputs"]:
        path = ROOT / item["path"]
        if not path.is_file():
            raise ValueError(f"PCFA-08 authority input missing: {item['path']}")
        bound = dict(item)
        bound["sha256"] = digest_file(path)
        authority_inputs.append(bound)
    record["authority_inputs"] = authority_inputs
    record["cross_authority_invariants"] = [
        {**item, "accepted": True} for item in source["cross_authority_invariants"]
    ]
    record["generated_from"] = str(SOURCE.relative_to(ROOT))
    plan = record["branch_cleanup_plan"]
    record["summary"] = {
        "authority_input_count": len(authority_inputs),
        "cross_authority_invariant_count": len(record["cross_authority_invariants"]),
        "manual_launch_gate_count": len(record["manual_launch_gates"]),
        "planned_branch_deletion_count": len(plan["delete_after_dependency_order_integration"]),
        "retained_branch_count_at_cleanup_completion": len(plan["retain_branches"]),
        "pcfa07_obligation_count": 93,
        "pcfa07_planned_test_count": 93,
        "new_imp_phase_count": 0,
        "new_imp_task_count": 0,
        "phase0_new_obligation_count": 0,
    }
    report = "\n".join(
        [
            "# PCFA-08 final pre-Codex cross-authority acceptance evidence",
            "",
            "<!-- Generated by scripts/build_pcfa08_final_acceptance.py. -->",
            "",
            "- Work package: `PCFA-08`",
            f"- Authority inputs SHA-256-bound: `{len(authority_inputs)}`",
            f"- Cross-authority invariants accepted: `{len(record['cross_authority_invariants'])}`",
            f"- Manual launch gates intentionally pending: `{len(record['manual_launch_gates'])}`",
            f"- Exact post-integration branch deletion plan: `{len(plan['delete_after_dependency_order_integration'])}` branches",
            "- Required final live branch inventory before Codex branch creation: `[\"main\"]`",
            "- Every deleted branch requires its final 40-hex SHA as retained evidence.",
            "- PCFA-07 remains exactly 93 obligations / 93 planned tests with zero IMP-P0 widening.",
            "- Repository-side final cross-authority acceptance: `true`.",
            "- Manual launch evidence complete: `false`.",
            "- `codex_start_authorized=false`; no implementation or branch creation is authorized by this package.",
            "",
        ]
    )
    return record, report


def _require(failures: list[str], condition: bool, message: str) -> None:
    if not condition:
        failures.append(message)


def record_failures(record: dict[str, Any]) -> list[str]:
    failures: list[str] = []
    acceptance = record.get("repository_acceptance", {})
    cleanup = record.get("branch_cleanup_plan", {})
    target = record.get("launch_target", {})
    boundaries = record.get("boundaries", {})
    summary = record.get("summary", {})
    invariants = record.get("cross_authority_invariants", [])
    manual = record.get("manual_launch_gates", [])
    authority = record.get("authority_inputs", [])

    _require(failures, record.get("work_package_id") == "PCFA-08", "PCFA-08 identity drifted")
    _require(
        failures,
        record.get("status") == "repository_cross_authority_accepted_manual_launch_gates_pending",
        "PCFA-08 status drifted",
    )
    _require(failures, len(authority) == 9, "PCFA-08 authority input count drifted")
    _require(
        failures,
        all(isinstance(item.get("sha256"), str) and len(item["sha256"]) == 64 for item in authority),
        "PCFA-08 authority digest binding is incomplete",
    )
    _require(
        failures,
        len(invariants) == 18 and all(item.get("accepted") is True for item in invariants),
        "PCFA-08 cross-authority invariants are incomplete",
    )
    _require(
        failures,
        acceptance.get("prior_pcfa_packages_required")
        == ["PCFA-01", "PCFA-02", "PCFA-03", "PCFA-04", "PCFA-05", "PCFA-06", "PCFA-07"],
        "PCFA-08 predecessor package coverage drifted",
    )
    _require(
        failures,
        acceptance.get("all_prior_repository_side_requirements_consistent") is True
        and acceptance.get("implementation_backlog_reconciled") is True
        and acceptance.get("phase0_scope_unchanged") is True
        and acceptance.get("repository_side_cross_authority_acceptance_complete") is True
        and acceptance.get("manual_launch_evidence_complete") is False
        and acceptance.get("launch_authorization_complete") is False,
        "PCFA-08 repository acceptance semantics drifted",
    )
    manual_ids = [item.get("id") for item in manual]
    _require(
        failures,
        manual_ids
        == [
            "repository_visibility_private_verified",
            "github_hosted_controls_verified",
            "historical_branch_cleanup_complete",
            "clean_macos_environment_verified",
            "live_issue_bodies_synchronized",
            "explicit_founder_phase0_approval_received",
            "approved_main_sha_bound",
            "launch_permit_issued",
        ],
        "PCFA-08 manual launch gate registry drifted",
    )
    _require(
        failures,
        all(item.get("required_value") is True and str(item.get("status", "")).startswith("pending_") for item in manual),
        "PCFA-08 manual launch gates must remain pending",
    )
    delete = cleanup.get("delete_after_dependency_order_integration", [])
    _require(failures, cleanup.get("policy") == "exact_allowlist_only", "PCFA-08 cleanup policy drifted")
    _require(
        failures,
        cleanup.get("observed_repository_branch_count_before_pcfa08_branch") == 65
        and cleanup.get("observed_non_main_branch_count_before_pcfa08_branch") == 64
        and cleanup.get("pcfa08_branch_added_after_observation") is True
        and cleanup.get("expected_cleanup_branch_count_after_pcfa08_integration") == 65,
        "PCFA-08 branch observation/count semantics drifted",
    )
    _require(
        failures,
        len(delete) == 65
        and len(set(delete)) == 65
        and "main" not in delete
        and all(isinstance(name, str) and name and not any(token in name for token in ("*", "?", "[", "]")) for name in delete),
        "PCFA-08 exact branch cleanup allowlist drifted",
    )
    _require(
        failures,
        cleanup.get("retain_branches") == ["main"]
        and cleanup.get("final_live_branch_inventory_must_equal") == ["main"]
        and cleanup.get("require_final_sha_for_every_deleted_branch") is True
        and cleanup.get("require_merged_ancestry_or_explicit_obsolete_classification") is True
        and cleanup.get("wildcards_prohibited") is True
        and cleanup.get("codex_phase0_branch_must_be_absent_before_cleanup_completion") is True
        and cleanup.get("unexpected_branch_requires_explicit_reconciliation") is True,
        "PCFA-08 branch cleanup evidence semantics drifted",
    )
    _require(
        failures,
        target
        == {
            "permitted_phase": "Codex Phase 0 only",
            "permitted_tasks": ["P0.1", "P0.2", "P0.3", "P0.4"],
            "required_branch": "codex/phase-0-foundation",
            "required_pull_request_state": "draft",
            "required_status_check": "Validate final pre-Codex canonical handoff and complete release",
            "implementation_may_start_only_after_valid_permit": True,
        },
        "PCFA-08 launch target drifted",
    )
    _require(
        failures,
        boundaries.get("founder_accountability_preserved") is True
        and all(value is False for key, value in boundaries.items() if key != "founder_accountability_preserved"),
        "PCFA-08 authorization boundary drifted",
    )
    _require(
        failures,
        summary
        == {
            "authority_input_count": 9,
            "cross_authority_invariant_count": 18,
            "manual_launch_gate_count": 8,
            "planned_branch_deletion_count": 65,
            "retained_branch_count_at_cleanup_completion": 1,
            "pcfa07_obligation_count": 93,
            "pcfa07_planned_test_count": 93,
            "new_imp_phase_count": 0,
            "new_imp_task_count": 0,
            "phase0_new_obligation_count": 0,
        },
        "PCFA-08 summary drifted",
    )
    return failures


def state_failures(state: dict[str, Any], record: dict[str, Any] | None = None) -> list[str]:
    value = record or load_json(RECORD)
    failures = record_failures(value)
    authority = state.get("current_authority", {})
    readiness = state.get("repository_readiness", {})
    manual = state.get("manual_launch_gates", {})
    target = state.get("launch_target", {})
    expected_digest = digest_file(RECORD) if RECORD.is_file() else None
    _require(
        failures,
        authority.get("final_pre_codex_cross_authority_acceptance")
        == "repository/pcfa08-final-pre-codex-cross-authority-acceptance.json"
        and authority.get("final_pre_codex_cross_authority_acceptance_sha256") == expected_digest,
        "current state does not bind PCFA-08 final acceptance",
    )
    _require(
        failures,
        readiness.get("pcfa08_final_cross_authority_acceptance_complete") is True,
        "current readiness omits PCFA-08 completion",
    )
    _require(
        failures,
        target.get("permitted_tasks") == ["P0.1", "P0.2", "P0.3", "P0.4"],
        "PCFA-08 state widened Phase 0",
    )
    _require(
        failures,
        manual.get("codex_start_authorized") is False and manual.get("launch_permit_issued") is False,
        "PCFA-08 state prematurely authorized launch",
    )
    _require(
        failures,
        state.get("launch_permit", {}).get("stale_on_pcfa08_final_acceptance_change") is True,
        "launch permit does not explicitly stale on PCFA-08 acceptance drift",
    )
    return failures


def hosted_cleanup_failures(
    record: dict[str, Any], hosted: dict[str, Any], live_branch_names: list[str]
) -> list[str]:
    failures = record_failures(record)
    plan = record["branch_cleanup_plan"]
    cleanup = hosted.get("branch_cleanup", {})
    deleted = cleanup.get("deleted_branches", [])
    expected_names = set(plan["delete_after_dependency_order_integration"])
    deleted_names = [item.get("branch") for item in deleted if isinstance(item, dict)]
    _require(
        failures,
        cleanup.get("complete") is True,
        "PCFA-08 exact branch cleanup is incomplete",
    )
    _require(
        failures,
        cleanup.get("remaining_branches") == ["main"],
        "PCFA-08 attested final branch inventory must contain only main",
    )
    _require(
        failures,
        sorted(live_branch_names) == ["main"],
        "live GitHub branch inventory must contain only main before Codex launch",
    )
    _require(
        failures,
        _DIGEST_RE.fullmatch(str(cleanup.get("inventory_sha256", ""))) is not None
        and cleanup.get("inventory_sha256") == _inventory_digest(live_branch_names),
        "branch inventory SHA-256 does not bind the independently observed live branch list",
    )
    _require(
        failures,
        len(deleted) == len(expected_names)
        and len(deleted_names) == len(set(deleted_names))
        and set(deleted_names) == expected_names,
        "deleted-branch evidence does not exactly cover the PCFA-08 allowlist",
    )
    _require(
        failures,
        all(
            isinstance(item, dict)
            and _SHA_RE.fullmatch(str(item.get("final_sha", ""))) is not None
            and item.get("disposition") in {"merged", "obsolete", "superseded"}
            for item in deleted
        ),
        "every deleted branch requires final SHA and governed disposition evidence",
    )
    return failures


def run_self_test(state: dict[str, Any]) -> int:
    record = load_json(RECORD)
    failures = state_failures(state, record)
    if failures:
        raise SystemExit("PCFA-08 final acceptance rejected: " + "; ".join(failures))
    mutations: list[tuple[str, tuple[str, ...], Any]] = [
        ("authority", ("current_authority", "final_pre_codex_cross_authority_acceptance"), "wrong.json"),
        ("digest", ("current_authority", "final_pre_codex_cross_authority_acceptance_sha256"), "0" * 64),
        ("readiness", ("repository_readiness", "pcfa08_final_cross_authority_acceptance_complete"), False),
        ("p0", ("launch_target", "permitted_tasks"), ["P0.1", "P1.1"]),
    ]
    rejected = 0
    for label, path, replacement in mutations:
        value = copy.deepcopy(state)
        node: Any = value
        for part in path[:-1]:
            node = node[part]
        node[path[-1]] = replacement
        if not state_failures(value, record):
            raise SystemExit(f"PCFA-08 state mutation not rejected: {label}")
        rejected += 1
    record_mutations: list[tuple[str, tuple[str, ...], Any]] = [
        ("invariant", ("cross_authority_invariants", "0", "accepted"), False),
        ("manual", ("repository_acceptance", "manual_launch_evidence_complete"), True),
        ("authorization", ("boundaries", "codex_start_authorized"), True),
        ("cleanup count", ("branch_cleanup_plan", "expected_cleanup_branch_count_after_pcfa08_integration"), 64),
        ("retain main", ("branch_cleanup_plan", "retain_branches"), ["main", "other"]),
        ("wildcard", ("branch_cleanup_plan", "delete_after_dependency_order_integration", "0"), "governance/*"),
        ("p0 target", ("launch_target", "permitted_tasks"), ["P0.1", "P1.1"]),
    ]
    for label, path, replacement in record_mutations:
        value = copy.deepcopy(record)
        node: Any = value
        for part in path[:-1]:
            node = node[int(part)] if part.isdigit() else node[part]
        final = path[-1]
        if final.isdigit():
            node[int(final)] = replacement
        else:
            node[final] = replacement
        if not record_failures(value):
            raise SystemExit(f"PCFA-08 record mutation not rejected: {label}")
        rejected += 1
    synthetic_hosted = {
        "branch_cleanup": {
            "complete": True,
            "remaining_branches": ["main"],
            "inventory_sha256": _inventory_digest(["main"]),
            "deleted_branches": [
                {"branch": name, "final_sha": "a" * 40, "disposition": "obsolete"}
                for name in record["branch_cleanup_plan"]["delete_after_dependency_order_integration"]
            ],
        }
    }
    if hosted_cleanup_failures(record, synthetic_hosted, ["main"]):
        raise SystemExit("PCFA-08 valid synthetic cleanup evidence was rejected")
    bad = copy.deepcopy(synthetic_hosted)
    bad["branch_cleanup"]["deleted_branches"][0]["final_sha"] = "bad"
    if not hosted_cleanup_failures(record, bad, ["main"]):
        raise SystemExit("PCFA-08 malformed cleanup SHA was not rejected")
    rejected += 1
    if not hosted_cleanup_failures(record, synthetic_hosted, ["main", "other"]):
        raise SystemExit("PCFA-08 live branch inventory drift was not rejected")
    rejected += 1
    return rejected


final_acceptance_failures = state_failures
