#!/usr/bin/env bash
set -euo pipefail

python scripts/build_test_registry.py
python scripts/build_pcr02_test_identity.py
python scripts/export_machine_contracts.py
python scripts/build_phase3_oracle.py
python scripts/build_phase4_deliverable_semantic_model.py
python scripts/build_phase5_fixture_programme.py
python scripts/build_phase6_knowledge_intelligence.py
python scripts/build_phase7_security_regionalisation.py
python scripts/build_pcr01_canonical_release.py
python scripts/build_pcr03_repository_hygiene.py
python scripts/build_pcr05_runtime_adapters.py
python scripts/build_pcr06_hermes_compatibility.py
python scripts/build_pcr07_northstar_blueprint.py
python scripts/build_pcr08_initial_operating_controls.py
python scripts/build_pcr09_codex_issue.py
python scripts/build_workstream6_handoff_reconciliation.py
python scripts/build_pcr04_codex_handoff.py
python scripts/build_pcr10_pre_codex_readiness.py
python scripts/build_workstream4_readiness.py
python scripts/build_workstream5_launch_control.py
python scripts/build_workstream6_final_reconciliation.py
python scripts/build_workstream6_final_launch_control.py
python scripts/build_workstream6_current_status.py
# WS6.5 and WS6.6 surface fingerprints are immutable package-time snapshots.
# WS6.14 revalidates their current semantic namespace/workflow decisions against live authority.
python scripts/build_workstream6_canonical_authority.py
python scripts/build_workstream6_configuration_contradictions.py
python scripts/build_workstream6_issue_backlog_normalization.py
python scripts/build_workstream6_implementation_obligation_map.py
python scripts/build_workstream6_developer_experience_specification.py
python scripts/build_workstream6_founder_experience_specification.py
python scripts/build_workstream6_deliverable_quality_implementation_specification.py
python scripts/build_workstream6_renderer_preimplementation_assets.py
python scripts/build_workstream6_operational_quality_specification.py
python scripts/build_workstream6_phase0_licence_decision_placeholder.py
python scripts/build_workstream6_cross_authority_consistency_gate.py
python scripts/build_workstream6_final_workflow.py
python scripts/build_workstream6_permanent_release_record.py
# Post-release PCFA authority is generated only after all immutable WS6 package snapshots.
python scripts/build_pcfa03_repository_posture.py
python scripts/build_pcfa04_product_scope_addendum.py
python scripts/build_pcfa05_mvcl.py
python scripts/build_pcfa06_hermes_refresh.py
python scripts/build_pcfa07_backlog_reconciliation.py
python scripts/build_pcfa08_final_acceptance.py
python scripts/build_pcfa02_current_operational_state.py

git diff --exit-code

python scripts/validate_phase1_contracts.py
python scripts/validate_phase2_agents.py
python scripts/validate_phase3_ai_audit_oracle.py
python scripts/validate_phase4_deliverable_semantic_model.py
python scripts/validate_phase5_fixture_programme.py
python scripts/validate_phase6_knowledge_intelligence.py
python scripts/validate_phase7_security_regionalisation.py
python scripts/validate_pcr01_canonical_release.py
python scripts/validate_pcr02_referential_integrity.py
python scripts/validate_pcr03_repository_hygiene.py
python scripts/validate_pcr05_runtime_adapters.py
python scripts/validate_pcr06_hermes_compatibility.py
python scripts/validate_pcr07_northstar_blueprint.py
python scripts/validate_pcr08_initial_operating_controls.py
python scripts/validate_pcr09_codex_issue.py
python scripts/validate_pcr04_codex_handoff.py
python scripts/validate_pcr10_pre_codex_readiness.py
python scripts/validate_workstream4_readiness.py
python scripts/validate_workstream5_launch_control.py
python scripts/validate_workstream6_final_reconciliation.py
python scripts/validate_workstream6_handoff_reconciliation.py
python scripts/validate_workstream6_final_launch_control.py
python scripts/validate_workstream6_current_status.py
# Current WS6.5 namespace and WS6.6 workflow identity semantics are checked by WS6.14.
python scripts/validate_workstream6_canonical_authority.py
python scripts/validate_workstream6_configuration_contradictions.py
python scripts/validate_workstream6_issue_backlog_normalization.py
python scripts/validate_workstream6_implementation_obligation_map.py
python scripts/validate_workstream6_developer_experience_specification.py
python scripts/validate_workstream6_founder_experience_specification.py
python scripts/validate_workstream6_deliverable_quality_implementation_specification.py
python scripts/validate_workstream6_renderer_preimplementation_assets.py
python scripts/validate_workstream6_operational_quality_specification.py
python scripts/validate_workstream6_phase0_licence_decision_placeholder.py
# WS6.14 validator asserts the pre-WS6.15 reserved workflow state; WS6.15 revalidates its current invariants.
# WS6.15 validator asserts the activation-package boundary; WS6.16 revalidates either the preparation
# state or the permanent post-merge release state, depending on whether the final record exists.
if [[ -f releases/pre-codex-final-reconciliation-2026-08-06.json ]]; then
  python scripts/require_workstream6_final_reconciliation.py
else
  python scripts/validate_workstream6_permanent_release_record.py
fi
python scripts/validate_pcfa01_launch_control.py
python scripts/validate_pcfa02_current_operational_state.py
python scripts/validate_pcfa03_repository_posture.py
python scripts/validate_pcfa04_product_scope_addendum.py
python scripts/validate_pcfa05_mvcl.py
python scripts/validate_pcfa06_hermes_refresh.py
python scripts/validate_pcfa07_backlog_reconciliation.py
python scripts/validate_pcfa08_final_acceptance.py
python scripts/prepare_codex_phase0_launch.py --self-test
python scripts/require_workstream6_final_reconciliation.py --self-test

(
  cd packages/offdata-core
  pytest --cov=offdata_core --cov-report=term-missing --cov-fail-under=90 | tee /tmp/ws62-pytest.log
  mypy src
)
python -m compileall -q packages/offdata-core/src packages/offdata-core/tests scripts
ruff check --config packages/offdata-core/pyproject.toml packages/offdata-core/src packages/offdata-core/tests scripts
